### ISSUE TITLE
html_embed doesn't work for attached images

### ISSUE THREAD

**Issue by waynebliu** [ipython-contrib/jupyter_contrib_nbextensions#1041]
!jupyter nbconvert --to html_embed embedhtmltest.ipynb

[NbConvertApp] Converting notebook embedhtmltest.ipynb to html_embed
Traceback (most recent call last):
  File "/home/wayne/miniconda3/envs/mypy/bin/jupyter-nbconvert", line 11, in <module>
    load_entry_point('nbconvert==5.2.1', 'console_scripts', 'jupyter-nbconvert')()
  File "/home/wayne/miniconda3/envs/mypy/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/wayne/miniconda3/envs/mypy/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/wayne/miniconda3/envs/mypy/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 313, in start
    self.convert_notebooks()
  File "/home/wayne/miniconda3/envs/mypy/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 481, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/home/wayne/miniconda3/envs/mypy/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 452, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/home/wayne/miniconda3/envs/mypy/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 381, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/home/wayne/miniconda3/envs/mypy/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 172, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/home/wayne/miniconda3/envs/mypy/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 190, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/home/wayne/miniconda3/envs/mypy/lib/python3.6/site-packages/jupyter_contrib_nbextensions/nbconvert_support/embedhtml.py", line 57, in from_notebook_node
    embedded_output = regex.sub(self.replfunc, output)
  File "/home/wayne/miniconda3/envs/mypy/lib/python3.6/site-packages/jupyter_contrib_nbextensions/nbconvert_support/embedhtml.py", line 35, in replfunc
    with open(url, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'attachment:2017-08-10-165533_1280x800_scrot.png'

**Comment by juhasch** [comment]
Thanks for reporting.
The exporter does not yet now about the new embedded image types.

Should be easy to fix, however might take a few days. If you want to take a look at is yourself, check `embedhtml.py` and prevent the exporter from doing anything if the image source is an attachment instead of a file or url.

**Comment by waynebliu** [comment]
I tried your code and it worked very well. Happy if this could be merged and released :)

Thanks!

**Comment by juhasch** [comment]
Thanks for the feedback.
