### ISSUE TITLE
No nbextensions match the applied filters!

### ISSUE THREAD

**Issue by vmjcv** [ipython-contrib/jupyter_contrib_nbextensions#1049]
![1](https://user-images.githubusercontent.com/25278695/29365974-3d879a50-82cb-11e7-8e57-54dcfdce1f46.jpg)
My install seems to have some problems:

No nbextensions match the applied filters.

I am going to install the method is

1. `conda install -c conda-forge jupyter_contrib_nbextensions`
2. `jupyter contrib nbextension install --sys-prefix`
3. `conda install -c conda-forge jupyter_nbextensions_configurator`

When i use this command:   `jupyter nbextension list`
I found some mistakes:

```
[root@mjc ~]# jupyter nbextension list
Known nbextensions:
  config dir: /root/.jupyter/nbconfig
    notebook section
      nbextensions_configurator/config_menu/main  enabled
      - Validating: problems found:
        - require?  X nbextensions_configurator/config_menu/main
      contrib_nbextensions_help_item/main  enabled
      - Validating: OK
      jupyter-js-widgets/extension  enabled
      - Validating: OK
      codefolding/main  enabled
      - Validating: OK
      /root/.local/share/jupyter/nbextensions/collapsible_headings/main  enabled
      - Validating: problems found:
        - require?  X /root/.local/share/jupyter/nbextensions/collapsible_headings/main
      collapsible_headings/main  enabled
      - Validating: OK
      collapsible_headings/maincollapsible_headings/main  enabled
      - Validating: problems found:
        - require?  X collapsible_headings/maincollapsible_headings/main
      nbextensions/collapsible_headings/main  enabled
      - Validating: problems found:
        - require?  X nbextensions/collapsible_headings/main
    tree section
      nbextensions_configurator/tree_tab/main  enabled
      - Validating: problems found:
        - require?  X nbextensions_configurator/tree_tab/main
Traceback (most recent call last):
  File "/home/anaconda3/bin/jupyter-nbextension", line 6, in <module>
    sys.exit(notebook.nbextensions.main())
  File "/home/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/anaconda3/lib/python3.6/site-packages/notebook/nbextensions.py", line 900, in start
    super(NBExtensionApp, self).start()
  File "/home/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/home/anaconda3/lib/python3.6/site-packages/notebook/nbextensions.py", line 872, in start
    self.list_nbextensions()
  File "/home/anaconda3/lib/python3.6/site-packages/notebook/nbextensions.py", line 855, in list_nbextensions
    data = cm.get(section)
  File "/home/anaconda3/lib/python3.6/site-packages/traitlets/config/manager.py", line 63, in get
    return json.load(f)
  File "/home/anaconda3/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/anaconda3/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 6 column 7 (char 100)
```

But I do not know how to solve it, hope someone can help me.
Of course there is a re-installation method is also very good
If this problem is very low, please help solve, I am a novice

**Comment by vmjcv** [comment]
Thanks for the help. I've solved the problem. I read the document and found it might be “edit. JSON” files are destroyed when they are read simultaneously, and I modified them to succeed

**Comment by jcb91** [comment]
> I read the document and found it might be “edit. JSON” files are destroyed when they are read simultaneously, and I modified them to succeed

I'm not really sure what you mean by this, but I'm glad you managed to fix your problem ok :smile:

**Comment by soamaven** [comment]
Just had the same problem, had to edit `etc/jupyter/nbconfig/notebook.json` in my sys-prefix path. May be in another path for other people. use `jupyter --paths` to manually check all the `.json` files for errors.

Mine was a trailing `,` at the end of a data block, i.e. 

`
{"someobject":
  {"someproperty": false,
   "anotherproperty": true,
  }
}
`

was the offending format. The trailing `,` is wrong syntax.

**Comment by invictuszhao** [comment]
I met the same matter, but haven't solved it after trying lots of methods, could you please show how you fix your problem
