### ISSUE TITLE
Cannot configure while the Jupyter notebook server

### ISSUE THREAD

**Issue by nick-youngblut** [ipython-contrib/jupyter_contrib_nbextensions#1090]
I'm trying to install the `jupyter_contrib_nbextensions` with conda. I get the following error when trying to install (here, just showing a subset of the error):

```
Traceback (most recent call last):
  File "/ebio/abt3_projects/small_projects/nyoungblut/dev/data_analysis_workshops/anaconda3/bin/jupyter-contrib-nbextension", line 11, in <module>
    load_entry_point('jupyter-contrib-nbextensions==0.3.1', 'console_scripts', 'jupyter-contrib-nbextension')()
  File "/ebio/abt3_projects/small_projects/nyoungblut/dev/data_analysis_workshops/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/ebio/abt3_projects/small_projects/nyoungblut/dev/data_analysis_workshops/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/ebio/abt3_projects/small_projects/nyoungblut/dev/data_analysis_workshops/anaconda3/lib/python3.6/site-packages/jupyter_contrib_nbextensions/application.py", line 226, in start
    super(ContribNbextensionsApp, self).start()
  File "/ebio/abt3_projects/small_projects/nyoungblut/dev/data_analysis_workshops/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/ebio/abt3_projects/small_projects/nyoungblut/dev/data_analysis_workshops/anaconda3/lib/python3.6/site-packages/jupyter_contrib_nbextensions/application.py", line 173, in start
    toggle_install_files(self._toggle_value, **kwargs_files)
  File "/ebio/abt3_projects/small_projects/nyoungblut/dev/data_analysis_workshops/anaconda3/lib/python3.6/site-packages/jupyter_contrib_nbextensions/install.py", line 60, in toggle_install_files
    'Cannot configure while the Jupyter notebook server is running')
jupyter_contrib_nbextensions.install.NotebookRunningError: Cannot configure while the Jupyter notebook server is running
```

The conda install prompt shows the following:

```
The following NEW packages will be INSTALLED:

    jupyter_contrib_core:              0.3.3-py36_0  conda-forge
    jupyter_nbextensions_configurator: 0.2.7-py36_0  conda-forge

The following packages will be SUPERSEDED by a higher-priority channel:

    conda:                             4.3.25-py36_0             --> 4.3.23-py36_0 conda-forge
    conda-env:                         2.6.0-0                   --> 2.6.0-0       conda-forge
```

I have other jupyter notebooks running but they are in different conda environments in different anaconda installs at various locations on the server. Why is `jupyter_contrib_nbextensions` assessing jupyter notebooks in other isolated conda environments? Do I have to shut down all notebooks in order to install `jupyter_contrib_nbextensions`?

**Comment by nick-youngblut** [comment]
My "Nbextensions configuration" looks like the following:

![screen shot 2017-09-13 at 10 22 31](https://user-images.githubusercontent.com/2468572/30367074-7cedf312-986d-11e7-8116-b8e084375c8e.png)


For all of the extensions, I get the following: `...but doesn't provide a yaml file to tell us how to configure it` 

However, the *.yaml files seem to be present:

```
data_analysis_workshops/anaconda3/pkgs/jupyter_contrib_nbextensions-0.3.1-py36_0/lib/python3.6/site-packages/jupyter_contrib_nbextensions/nbextensions/python-markdown/python-markdown.yaml
data_analysis_workshops/anaconda3/pkgs/jupyter_contrib_nbextensions-0.3.1-py36_0/lib/python3.6/site-packages/jupyter_contrib_nbextensions/nbextensions/codefolding/codefolding.yaml
data_analysis_workshops/anaconda3/pkgs/jupyter_contrib_nbextensions-0.3.1-py36_0/lib/python3.6/site-packages/jupyter_contrib_nbextensions/nbextensions/codefolding/codefolding_editor.yaml
data_analysis_workshops/anaconda3/pkgs/jupyter_contrib_nbextensions-0.3.1-py36_0/lib/python3.6/site-packages/jupyter_contrib_nbextensions/nbextensions/runtools/runtools.yaml
data_analysis_workshops/anaconda3/pkgs/jupyter_contrib_nbextensions-0.3.1-py36_0/lib/python3.6/site-packages/jupyter_contrib_nbextensions/nbextensions/scroll_down/config.yaml
... [a total of 58 *.yaml files in this directory]
```

**Comment by jcb91** [comment]
> I have other jupyter notebooks running but they are in different conda environments in different anaconda installs at various locations on the server. Why is `jupyter_contrib_nbextensions` assessing jupyter notebooks in other isolated conda environments? Do I have to shut down all notebooks in order to install `jupyter_contrib_nbextensions`?

So the install command uses the [`notebook.notebookapp.list_running_servers`](https://github.com/jupyter/notebook/blob/60f81e49b21320b694cb57707c59dd7b47fcf021/notebook/notebookapp.py#L1504-L1532) function. Although this allows you to specify a runtime directory in which  to check for servers, the default [jupyter runtime directory](https://github.com/jupyter/jupyter_core/blob/d98cfbeb5bd6f790ee434c50ed52a29fd1d4c44a/jupyter_core/paths.py#L88-L110) is set system-wide, so there isn't really a reliable way to distinguish between environments. Personally, I don't think installing while notebook servers are running is a problem at all, excepting the rare case where a config file gets edited while the notebook server is reading it, which I think is probably rare enough to consider acceptable. Certainly other extensions like [`nb_conda_kernels`](https://github.com/Anaconda-Platform/nb_conda_kernels/blob/f7b468090fc2f7fbf1dd56fe875f3e5c28051aa9/nb_conda_kernels/install.py) and [`nb_anacondacloud`](https://github.com/conda-forge/nb_anacondacloud-feedstock/blob/063556a52f1e7995c3c759016fc34f70239869c7/recipe/post-link.bat#L3-L4) don't bother with this check.

Anyway, since it's part of the post-link step in the conda install, the python package gets installed ok (as you have observed, all the yaml files are present in the python package's `nbextensions` directory), and you can manually run the second step of the [install](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/blob/53e3addfe8b6019f90ee7421006b0f5ca5cc1d75/README.md#2-install-javascript-and-css-files) ignoring running servers, using

    jupyter contrib nbextensions install --sys-prefix --skip-running-check

from the appropriate conda environment.

To clarify, the reason all the yaml files are present, but not found by the notebook server, is that the notebook server looks for nbextensions in the [jupyter path](https://github.com/jupyter/jupyter_core/blob/d98cfbeb5bd6f790ee434c50ed52a29fd1d4c44a/jupyter_core/paths.py#L128-L162), but the yaml files you've found are part of the python package (for distribution) and haven't been correctly copied into any of the jupyter data directories.

I hope some of that makes sense - let me know if not.

Any thoughts on removing/making non-default the running check @nick-youngblut, @jfbercher @juhasch?

**Comment by nick-youngblut** [comment]
Thanks for the clarification! I tried `jupyter contrib nbextensions install --sys-prefix --skip-running-check` and just got the following: 

```
community-contributed spice for Jupyter Interactive Computing

Options
-------

Arguments that take values are actually convenience aliases to full
Configurables, whose aliases are listed on the help line. For more information
on full configurables, see '--help-all'.

--debug
    set log level to logging.DEBUG (maximize logging output)
--generate-config
    generate default config file
-y
    Answer yes to any questions instead of prompting.
--log-level=<Enum> (Application.log_level)
    Default: 30
    Choices: (0, 10, 20, 30, 40, 50, 'DEBUG', 'INFO', 'WARN', 'ERROR', 'CRITICAL')
    Set the log level by value or name.
--config=<Unicode> (JupyterApp.config_file)
    Default: ''
    Full path of a config file.

To see all available configurables, use `--help-all`

[JupyterContribApp] CRITICAL | Bad config encountered during initialization:
[JupyterContribApp] CRITICAL | Unrecognized flag: '--sys-prefix'
```

I'm guessing that I should be using different options rather than: `--sys-prefix` and `--skip-running-check`.

**Comment by jcb91** [comment]
blegh, try

    jupyter contrib nbextension

without the `s`? Or possibly even 

    jupyter-contrib-nbextension

**Comment by nick-youngblut** [comment]
`jupyter-contrib -h` and `jupyter-contrib nbextension -h` produce the same output on options: 

```
community-contributed spice for Jupyter Interactive Computing

Options
-------

Arguments that take values are actually convenience aliases to full
Configurables, whose aliases are listed on the help line. For more information
on full configurables, see '--help-all'.

--debug
    set log level to logging.DEBUG (maximize logging output)
--generate-config
    generate default config file
-y
    Answer yes to any questions instead of prompting.
--log-level=<Enum> (Application.log_level)
    Default: 30
    Choices: (0, 10, 20, 30, 40, 50, 'DEBUG', 'INFO', 'WARN', 'ERROR', 'CRITICAL')
    Set the log level by value or name.
--config=<Unicode> (JupyterApp.config_file)
    Default: ''
    Full path of a config file.

To see all available configurables, use `--help-all'`
```

I'm not see where `--sys-prefix` or `--skip-running` come in to play.

**Comment by jcb91** [comment]
Yeah, the help message is for the jupyter-contrib script, which *should* find the nbextension subcommand (which accepts the flags) from pkg_resources. Perhaps the subcommand script hasn't been installed correctly 🤔

**Comment by jcb91** [comment]
You could alternatively do this in python, I guess:

```python
from jupyter_contrib_nbextensions.install import toggle_install

toggle_install(True, sys_prefix=True, skip_running_check=True)
```

**Comment by juhasch** [comment]
`jupyter-contrib-nbextension  install --help-all` or `jupyter-contrib-nbextension  install --help-all` will give you the options.

**Comment by nick-youngblut** [comment]
Yeah, `conda install -c conda-forge jupyter_contrib_nbextensions` failed due to the error: ` Cannot configure while the Jupyter notebook server is running`, which is probably why the `nbextensions` subcommand is not found.

**Comment by nick-youngblut** [comment]
`jupyter-contrib-nbextension` isn't installed due to the failed install (the error: `Cannot configure while the Jupyter notebook server is running`).

**Comment by jcb91** [comment]
Weird, that script should get copied as part of the python package install (which seems to have happened ok), before the post-link script (which is what fails). Oh well, it's not super important, as it doesn't do much beyond install/uninstall. Given all these complications, you may be better off following the pip package installation instructions from scratch, using the `--sys-prefix` and `--skip-running-check` flags...

**Comment by nick-youngblut** [comment]
OK, the following worked:

```
pip install jupyter_contrib_nbextensions
jupyter contrib nbextensions install --sys-prefix --skip-running-check
```

Thanks for your help!

**Comment by lportelli4** [comment]
I had this same issue even though I had close all my my notebooks and restarted my computer. The final comment worked for me!

**Comment by IreneCrisologo** [comment]
I had this issue too and like @lportelli4 I closed all my notebooks and restarted the pc. The final comment (by @nick-youngblut ) solved it!

**Comment by jcb91** [comment]
Hmm, it seems like the notebook code for detecting running servers is throwing up false positives then 🤔😞

**Comment by juhasch** [comment]
This is being discussed in https://github.com/jupyter/notebook/issues/2829

I guess we should add the `--skip-running-check` flag to the troubleshooting documentation.

**Comment by juhasch** [comment]
See PR #1100

**Comment by helixg** [comment]
I restarted my macbook and the last comment contributed by@nick-youngblut worked.
My problem was I have both py2 and py3 environment, and my jupyter notebook is running on py3 while i try to install the nbextension on py2 environment. That's why i failed.

**Comment by xshi0001** [comment]
I have problem on the second command `jupyter_contrib_nbextensions` when use pip : `pip install jupyter_contrib_nbextensions` 
![image](https://user-images.githubusercontent.com/28589533/34079940-e1b479ac-e371-11e7-98c2-99dd569d6d13.png)
 and I try to use  conda:
the same result ：
![image](https://user-images.githubusercontent.com/28589533/34079988-8592ca2e-e372-11e7-9082-84febf460178.png)
![image](https://user-images.githubusercontent.com/28589533/34079991-9156f43e-e372-11e7-96ea-d806702d2dbd.png)

**Comment by juhasch** [comment]
So it looks like you have a stale nbserver list. This seems to happen sometimes with the notebook.

To clean this up, try executing `jupyter --path`:
```
(py36) imac:~ juhasch$ jupyter --path
config:
    /Users/juhasch/.jupyter
    /Users/juhasch/anaconda3/envs/py36/etc/jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /Users/juhasch/Library/Jupyter
    /Users/juhasch/anaconda3/envs/py36/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /Users/juhasch/Library/Jupyter/runtime
```

Then you will find the stale file in the runtime directory:
```
(py36) imac:~ juhasch$ ls -al /Users/juhasch/Library/Jupyter/runtime/nbser*
-rw-r--r--  1 juhasch  staff  264 14 Dez 20:30 /Users/juhasch/Library/Jupyter/runtime/nbserver-19710.json
```
If you remove it, `jupyter notebook list` should not report any running servers.

**Comment by xshi0001** [comment]
That's meaning that I need to `rmdir` the runtime file?
![image](https://user-images.githubusercontent.com/28589533/34080299-9c7d9792-e376-11e7-8d07-a5835aca9240.png)
![image](https://user-images.githubusercontent.com/28589533/34080332-04ac3bd4-e377-11e7-8943-3dc095ebb251.png)

**Comment by juhasch** [comment]
You need to remove the `nbserver*.json` file. The `kernel*.json` files can be removed too, I guess.
I would not remove the `notebook_cookie_secret` file, otherwise I believe your existing notebooks will become untrusted (if you care about that).

**Comment by xshi0001** [comment]
Thank you for your kind help, solve the problem  of `Cannot configure while the Jupyter notebook server is running`,  but  a new problem has occur  as the nick-youngbl
![image](https://user-images.githubusercontent.com/28589533/34080603-ef4d6e02-e37b-11e7-9eaf-5ced8d7c2979.png)
 and  I try this way to install  a new nbextension by this way:
![image](https://user-images.githubusercontent.com/28589533/34080610-14c5e4de-e37c-11e7-9f93-81d5acac0ad0.png)
such as I want to use the function of  table of contents (2)
![image](https://user-images.githubusercontent.com/28589533/34080612-2b66fffc-e37c-11e7-8722-0135929a30bf.png)
 but the problem is that:
![image](https://user-images.githubusercontent.com/28589533/34080664-b0973318-e37c-11e7-9771-02d878d00c46.png)

**Comment by xshi0001** [comment]
what a big trouble for me to solve it!!!,   for pc：windows, `jupyter contrib nbextension install --user' may just do the first things ,and do not do the second. (I guess) . so I need to copy all the extension files into  C:\ProgramData\jupyter\nbextensions (the file nbextensions  do not include anything ,though I have use the command `jupyter contrib nbextension install --user' in cmd)
![image](https://user-images.githubusercontent.com/28589533/34081102-693d716a-e383-11e7-9fea-d131ba679818.png)

after I copy all the css and others into it.my notebook has changed!
![image](https://user-images.githubusercontent.com/28589533/34081168-4d766206-e384-11e7-867e-ef19853f9ef2.png)

**Comment by quant-dc** [comment]
I had this issue too, for me it appeared to be caused by installing jupyter_nbextensions_configurator in isolation prior to jupyter_contrib_nbextensions.

My solution:
`conda remove jupyter_nbextensions_configurator`

`conda install -c conda_forge jupyter_contrib_nbextensions`

(I installed the configurator first as part of BeakerX)

**Comment by edrexplore** [comment]
@quant-dc when I tried your solution I got the following message...


```
PackagesNotFoundError: The following packages are missing from the target environment:
  - jupyter_nbextensions_configurator
```


I still don't have the extensions installed and still keep on getting this error message 


```
jupyter_contrib_nbextensions.install.NotebookRunningError: Cannot configure while the Jupyter notebook server is running
```

when I run:
`conda install -c conda-forge jupyter_contrib_nbextensions`

**Comment by wardwissner** [comment]
this may be very unscientific but I uninstalled nb_extensions configurator
jupyter contrib nbextension uninstall --system

I reinstalled the package and it works

**Comment by li11112223** [comment]
> OK, the following worked:
> 
> ```
> pip install jupyter_contrib_nbextensions
> jupyter contrib nbextensions install --sys-prefix --skip-running-check
> ```
> it works
> Thanks for your help,bro
