### ISSUE TITLE
Problem installing nbextension

### ISSUE THREAD

**Issue by brianrobinson** [ipython-contrib/jupyter_contrib_nbextensions#1151]
Hello, I am having an issue with step 2 of the installation "jupyter contrib nbextension install --system"

```
C:\Windows\system32>jupyter contrib nbextension install --system
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\jupyter-contrib.EXE\__main__.py", line 9, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "c:\programdata\anaconda3\lib\site-packages\traitlets\config\application.py", line 656, in launch_instance
    app = cls.instance(**kwargs)
  File "c:\programdata\anaconda3\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "c:\programdata\anaconda3\lib\site-packages\jupyter_contrib_core\application.py", line 27, in __init__
    self._refresh_subcommands()
  File "c:\programdata\anaconda3\lib\site-packages\jupyter_contrib_core\application.py", line 43, in _refresh_subcommands
    get_subcommands_dict = entrypoint.load()
  File "c:\programdata\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2258, in load
  File "c:\programdata\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2264, in resolve
  File "c:\programdata\anaconda3\lib\site-packages\jupyter_contrib_nbextensions\application.py", line 15, in <module>
    from jupyter_contrib_nbextensions.install import (
  File "c:\programdata\anaconda3\lib\site-packages\jupyter_contrib_nbextensions\install.py", line 21, in <module>
    import jupyter_contrib_nbextensions.nbconvert_support
  File "c:\programdata\anaconda3\lib\site-packages\jupyter_contrib_nbextensions\nbconvert_support\__init__.py", line 6, in <module>
    from .embedhtml import EmbedHTMLExporter
  File "c:\programdata\anaconda3\lib\site-packages\jupyter_contrib_nbextensions\nbconvert_support\embedhtml.py", line 6, in <module>
    import lxml.etree as et
ImportError: DLL load failed: The specified procedure could not be found.
```

**Comment by jcb91** [comment]
hmm. Looks like your lxml package is attempting to load something from a DLL, but either the library or the relevant method couldn't be found. This is essentially an issue with your lxml package, which should either ship the required DLL itself, or be sure that it will be available in some other manner. How did you install lxml?

**Comment by brianrobinson** [comment]
I reinstalled lxml and everything works well. Thanks!

**Comment by jcb91** [comment]
Great, thanks for the report!
