### ISSUE TITLE
conda-forge: Dependency "libiconv" missing 

### ISSUE THREAD

**Issue by cbyrohl** [ipython-contrib/jupyter_contrib_nbextensions#1153]
Hi there,

running (anaconda 5 on python 2.7)

```
conda install -c conda-forge jupyter_contrib_nbextensions
```

on a clean install yields:

```
LinkError: post-link script failed for package conda-forge::jupyter_contrib_nbextensions-0.3.3-py27_0
running your command again with `-v` will provide additional information
location of failed script: /home/uni09/cosmo/cbyrohl/anaconda3/envs/py27/bin/.jupyter_contrib_nbextensions-post-link.sh
==> script messages <==
+ /home/uni09/cosmo/cbyrohl/anaconda3/envs/py27/bin/jupyter-contrib-nbextension install --sys-prefix
Traceback (most recent call last):
  File "/home/uni09/cosmo/cbyrohl/anaconda3/envs/py27/bin/jupyter-contrib-nbextension", line 11, in <module>
    load_entry_point('jupyter-contrib-nbextensions==0.3.3', 'console_scripts', 'jupyter-contrib-nbextension')()
  File "/home/uni09/cosmo/cbyrohl/anaconda3/envs/py27/lib/python2.7/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/uni09/cosmo/cbyrohl/anaconda3/envs/py27/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2751, in load_entry_point
    return ep.load()
  File "/home/uni09/cosmo/cbyrohl/anaconda3/envs/py27/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/home/uni09/cosmo/cbyrohl/anaconda3/envs/py27/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/uni09/cosmo/cbyrohl/anaconda3/envs/py27/lib/python2.7/site-packages/jupyter_contrib_nbextensions/application.py", line 15, in <module>
    from jupyter_contrib_nbextensions.install import (
  File "/home/uni09/cosmo/cbyrohl/anaconda3/envs/py27/lib/python2.7/site-packages/jupyter_contrib_nbextensions/install.py", line 21, in <module>
    import jupyter_contrib_nbextensions.nbconvert_support
  File "/home/uni09/cosmo/cbyrohl/anaconda3/envs/py27/lib/python2.7/site-packages/jupyter_contrib_nbextensions/nbconvert_support/__init__.py", line 6, in <module>
    from .embedhtml import EmbedHTMLExporter
  File "/home/uni09/cosmo/cbyrohl/anaconda3/envs/py27/lib/python2.7/site-packages/jupyter_contrib_nbextensions/nbconvert_support/embedhtml.py", line 6, in <module>
    import lxml.etree as et
ImportError: libiconv.so.2: cannot open shared object file: No such file or directory
```

Running 
```
conda install libiconv
```

and rerunning the installation of nbextensions finishes successfully. Is it possible to add libiconv to the dependency list so that it is automatically installed rather than running into this error?

Best,

**Comment by jcb91** [comment]
Libicon isn't a direct dependency of this repo, it's imported  by lxml, so this issue & the dependency belong on the lxml package really. Could you check whether it came from conda-forge (`conda list`)?

**Comment by cbyrohl** [comment]
Okay apparently my installation is not clean. For a clean setup

```
conda create -n test python=2.7
source activate test
conda install -c conda-forge jupyter_contrib_nbextensions
```

works flawlessly. All packages are provided by conda-forge (including lxml and libiconv).

For the faulty setup, lxml was detected as dependency and installed along with nbextensions

```
lxml                      4.1.0                    py27_0    conda-forge
```

Any way to trace this back any further?

**Comment by jcb91** [comment]
So in that case, it seems like the anaconda-provided lxml package is missing a dependency on libiconv, whereas the conda-forge version has correctly specified it. Best in that case to raise an issue with the anaconda folks

**Comment by jcb91** [comment]
Possibly. Not immediately sure. Could you try doing the same test setup, but install lxml _not_ from conda-forge prior to the nbextensions install?

**Comment by cbyrohl** [comment]
On my default setup:
```
> conda remove lxml libiconv
> conda install -c conda-forge lxml
The following NEW packages will be INSTALLED:
    libiconv: 1.14-4       conda-forge
    libxml2:  2.9.5-1      conda-forge
    libxslt:  1.1.29-5     conda-forge
    lxml:     4.1.0-py27_0 conda-forge
> conda install lxml
The following NEW packages will be INSTALLED:
    libxml2: 2.9.4-h6b072ca_5    
    libxslt: 1.1.29-hcf9102b_5   
    lxml:    4.1.0-py27hb025457_0
```

While a clean setup yields:

```
> conda install -c conda-forge lxml
The following NEW packages will be INSTALLED:
    libiconv: 1.14-4       conda-forge
    libxml2:  2.9.5-1      conda-forge
    libxslt:  1.1.29-5     conda-forge
    lxml:     4.1.0-py27_0 conda-forge
> conda install lxml
The following NEW packages will be INSTALLED:
    libiconv: 1.15-h63c8f33_5     
    libxml2:  2.9.4-0             
    libxslt:  1.1.29-0            
    lxml:     4.1.0-py27hb025457_0
```

So for some reason my setup does not download libiconv for the official anaconda channel. Therefore, this is indeed not an issue with jupyter_contrib_nbextensions. Do you think https://github.com/ContinuumIO/anaconda-issues/issues would be a good starting point or anything more specific?

**Comment by jcb91** [comment]
> So for some reason my setup does not download libiconv for the official anaconda channel. Therefore, this is indeed not an issue with jupyter_contrib_nbextensions.

Ok, thanks for taking the time to check this out!

> Do you think https://github.com/ContinuumIO/anaconda-issues/issues would be a good starting point or anything more specific?

I don't know of any more specific place to report issues with official anaconda packages, so I'd start there. They've been pretty responsive in the past, I think :)

**Comment by cbyrohl** [comment]
Will do, thanks!
