### ISSUE TITLE
Installation error - Ubuntu (with conda)

### ISSUE THREAD

**Issue by sensharma** [ipython-contrib/jupyter_contrib_nbextensions#1159]
I am getting the following error when trying to install with conda on Ubuntu 16.04. I have an environment in python 3.6 where I am trying to install this. Any suggestions? Thanks.

`

    Traceback (most recent call last):
      File "/home/chirantan/miniconda3/lib/python3.5/site-packages/conda/core/link.py", line 497, in run_script
        subprocess_call(command_args, env=env, path=dirname(path))
      File "/home/chirantan/miniconda3/lib/python3.5/site-packages/conda/gateways/subprocess.py", line 56, in subprocess_call
        output=_format_output(command_str, path, rc, stdout, stderr))
    subprocess.CalledProcessError: Command '['/bin/bash', '-x', '/home/chirantan/miniconda3/envs/fastai/bin/.jupyter_contrib_nbextensions-post-link.sh']' returned non-zero exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/chirantan/miniconda3/lib/python3.5/site-packages/conda/core/link.py", line 327, in _execute_actions
        run_script(target_prefix, Dist(pkg_data), 'post-unlink' if is_unlink else 'post-link')
      File "/home/chirantan/miniconda3/lib/python3.5/site-packages/conda/core/link.py", line 513, in run_script
        raise LinkError(message)
    conda.exceptions.LinkError: post-link script failed for package conda-forge::jupyter_contrib_nbextensions-0.3.3-py36_0
    running your command again with `-v` will provide additional information
    location of failed script: /home/chirantan/miniconda3/envs/fastai/bin/.jupyter_contrib_nbextensions-post-link.sh
    ==> script messages <==
    + /home/chirantan/miniconda3/envs/fastai/bin/jupyter-contrib-nbextension install --sys-prefix
    Traceback (most recent call last):
      File "/home/chirantan/miniconda3/envs/fastai/bin/jupyter-contrib-nbextension", line 11, in <module>
        load_entry_point('jupyter-contrib-nbextensions==0.3.3', 'console_scripts', 'jupyter-contrib-nbextension')()
      File "/home/chirantan/miniconda3/envs/fastai/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
        return get_distribution(dist).load_entry_point(group, name)
      File "/home/chirantan/miniconda3/envs/fastai/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
        return ep.load()
      File "/home/chirantan/miniconda3/envs/fastai/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2409, in load
        return self.resolve()
      File "/home/chirantan/miniconda3/envs/fastai/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2415, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/home/chirantan/miniconda3/envs/fastai/lib/python3.6/site-packages/jupyter_contrib_nbextensions/application.py", line 15, in <module>
        from jupyter_contrib_nbextensions.install import (
      File "/home/chirantan/miniconda3/envs/fastai/lib/python3.6/site-packages/jupyter_contrib_nbextensions/install.py", line 21, in <module>
        import jupyter_contrib_nbextensions.nbconvert_support
      File "/home/chirantan/miniconda3/envs/fastai/lib/python3.6/site-packages/jupyter_contrib_nbextensions/nbconvert_support/__init__.py", line 6, in <module>
        from .embedhtml import EmbedHTMLExporter
      File "/home/chirantan/miniconda3/envs/fastai/lib/python3.6/site-packages/jupyter_contrib_nbextensions/nbconvert_support/embedhtml.py", line 6, in <module>
        import lxml.etree as et
    ImportError: libicui18n.so.58: cannot open shared object file: No such file or directory
`

**Comment by juhasch** [comment]
This looks like a problem with the lxml installation and similar to #1153.

Can you try to repeat the steps in #1153 and reinstall lxml using conda-forge ?

```
conda create -n test python
source activate test
conda install -c conda-forge jupyter_contrib_nbextensions
```

**Comment by sensharma** [comment]
@juhasch Thanks! It works fine on a fresh env. I tried to follow the #1153 steps, remove and reinstall lxml and libiconv from conda-forge, but that still doesn't work for me in my existing env. Do you think I have to set up my original environment from scratch again? There's a lot of stuff in there, so I would prefer not to have to do that.

**Comment by jcb91** [comment]
@sensharma from a little digging, it seems this may come from the conda-forge channel using different versions of ICU to the defaults channel (see https://github.com/conda-forge/geopandas-feedstock/issues/21, and the conda forge note about multiple channels at https://conda-forge.org/docs/conda-forge_gotchas.html#using-multiple-channels). You could try making conda-forge the higher priority channel & upgrading packages, to try to force using the 58 version, I guess?
