### ISSUE TITLE
Lots of link errors when removing an env with nbextensions installed

### ISSUE THREAD

**Issue by moorepants** [ipython-contrib/jupyter_contrib_nbextensions#1163]
From a `conda env remove -n test-env` command:

```
+ /opt/conda/envs/test-env/bin/jupyter-contrib-nbextension uninstall --sys-prefix
Traceback (most recent call last):
  File "/opt/conda/envs/test-env/bin/jupyter-contrib-nbextension", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/opt/conda/envs/test-env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3049, in <module>
    @_call_aside
  File "/opt/conda/envs/test-env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3033, in _call_aside
    f(*args, **kwargs)
  File "/opt/conda/envs/test-env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3062, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/conda/envs/test-env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 658, in _build_master
    ws.require(__requires__)
  File "/opt/conda/envs/test-env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 972, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/conda/envs/test-env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 858, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'ipython_genutils' distribution was not found and is required by notebook, jupyter-contrib-nbextensions, traitlets

WARNING conda.core.link:run_script(516): pre-unlink script failed for package conda-forge::jupyter_contrib_nbextensions-0.3.1-py36_0
consider notifying the package maintainer
+ /opt/conda/envs/test-env/bin/python -c 'import logging; from jupyter_contrib_core.notebook_compat.nbextensions import uninstall_nbextension_python; uninstall_nbextension_python('\''jupyter_highlight_selected_word'\'', sys_prefix=True, logger=logging.getLogger())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'jupyter_contrib_core.notebook_compat.nbextensions'

WARNING conda.core.link:run_script(516): pre-unlink script failed for package conda-forge::jupyter_highlight_selected_word-0.0.11-py36_0
consider notifying the package maintainer
+ /opt/conda/envs/test-env/bin/python -c 'import logging; from jupyter_contrib_core.notebook_compat.nbextensions import uninstall_nbextension_python; uninstall_nbextension_python('\''latex_envs'\'', sys_prefix=True, logger=logging.getLogger())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'jupyter_contrib_core.notebook_compat.nbextensions'

WARNING conda.core.link:run_script(516): pre-unlink script failed for package conda-forge::jupyter_latex_envs-1.3.8.2-py36_1
consider notifying the package maintainer
+ /opt/conda/envs/test-env/bin/jupyter-nbextensions_configurator disable --sys-prefix
Traceback (most recent call last):
  File "/opt/conda/envs/test-env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2827, in _dep_map
    return self.__dep_map
  File "/opt/conda/envs/test-env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2638, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/test-env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2818, in _parsed_pkg_info
    return self._pkg_info
  File "/opt/conda/envs/test-env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2638, in __getattr__
    raise AttributeError(attr)
AttributeError: _pkg_info

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/test-env/bin/jupyter-nbextensions_configurator", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/opt/conda/envs/test-env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3049, in <module>
    @_call_aside
  File "/opt/conda/envs/test-env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3033, in _call_aside
    f(*args, **kwargs)
  File "/opt/conda/envs/test-env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3062, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/conda/envs/test-env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 658, in _build_master
    ws.require(__requires__)
  File "/opt/conda/envs/test-env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 972, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/conda/envs/test-env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 866, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/opt/conda/envs/test-env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2582, in requires
    dm = self._dep_map
  File "/opt/conda/envs/test-env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2829, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/opt/conda/envs/test-env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2838, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "/opt/conda/envs/test-env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2820, in _parsed_pkg_info
    metadata = self.get_metadata(self.PKG_INFO)
  File "/opt/conda/envs/test-env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1472, in get_metadata
    value = self._get(self._fn(self.egg_info, name))
  File "/opt/conda/envs/test-env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1581, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/conda/envs/test-env/lib/python3.6/site-packages/jupyter_core-4.3.0.dist-info/METADATA'

WARNING conda.core.link:run_script(516): pre-unlink script failed for package conda-forge::jupyter_nbextensions_configurator-0.2.7-py36_0
consider notifying the package maintainer
WARNING conda.core.link:run_script(516): pre-unlink script failed for package conda-forge::jupyterlab-0.27.0-py36_1
consider notifying the package maintainer
Traceback (most recent call last):
  File "/opt/conda/envs/test-env/bin/jupyter-nbextension", line 4, in <module>
    import notebook.nbextensions
  File "/opt/conda/envs/test-env/lib/python3.6/site-packages/notebook/__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "/opt/conda/envs/test-env/lib/python3.6/site-packages/notebook/nbextensions.py", line 23, in <module>
    from jupyter_core.paths import (
ModuleNotFoundError: No module named 'jupyter_core.paths'
Traceback (most recent call last):
  File "/opt/conda/envs/test-env/bin/jupyter-nbextension", line 4, in <module>
    import notebook.nbextensions
  File "/opt/conda/envs/test-env/lib/python3.6/site-packages/notebook/__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "/opt/conda/envs/test-env/lib/python3.6/site-packages/notebook/nbextensions.py", line 23, in <module>
    from jupyter_core.paths import (
ModuleNotFoundError: No module named 'jupyter_core.paths'
Traceback (most recent call last):
  File "/opt/conda/envs/test-env/bin/jupyter-serverextension", line 4, in <module>
    import notebook.serverextensions
  File "/opt/conda/envs/test-env/lib/python3.6/site-packages/notebook/__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "/opt/conda/envs/test-env/lib/python3.6/site-packages/notebook/nbextensions.py", line 23, in <module>
    from jupyter_core.paths import (
ModuleNotFoundError: No module named 'jupyter_core.paths'

WARNING conda.core.link:run_script(516): pre-unlink script failed for package conda-forge::nbgrader-0.5.3-py36_0
consider notifying the package maintainer
WARNING conda.core.link:run_script(516): pre-unlink script failed for package conda-forge::widgetsnbextension-3.0.3-py36_2
consider notifying the package maintainer
```

**Comment by jcb91** [comment]
This is because conda has no way for recipes to specify uninstall dependencies, so when removing packages, the order in which they get removed is, if not undefined, at least not controllable. This means the pre-unlink scripts can fail to import modules, and therefore fail. If you're removing everything, it shouldn't cause any problems, though.

**Comment by moorepants** [comment]
Thanks. Should I report this upstream?

**Comment by jcb91** [comment]
NP. I think it should be covered by https://github.com/conda/conda/issues/5417

**Comment by jcb91** [comment]
In fact, it seems as though it may even have been fixed in conda 4.4.0 :tada:

**Comment by jakirkham** [comment]
Should this be closed?
