### ISSUE TITLE
NotADirectoryError: jupyter_highlight_selected_word-0.1.0-py3.6.egg

### ISSUE THREAD

**Issue by jhgoebbert** [ipython-contrib/jupyter_contrib_nbextensions#1269]
Hi,

installing `jupyter_highlight_selected_word` tries to open/create files inside of the directory
`[PYPATH]/lib/python3.6/site-packages/jupyter_highlight_selected_word-0.1.0-py3.6.egg`

But this is a file => `NotADirectoryError: [Errno 20] Not a directory`
We get this error with 0.4.0 and 0.3.3 (which both include jupyter_highlight_selected_word 0.1.0).

Best,
Jens Henrik

P.S:
Here PYPATH is `/usr/local/software/jureca/Stages/Devel-2017b/software/Jupyter/2017b-test-gpsolf-2017b-Python-3.6.3`

P.P.S:

```
> `jupyter contrib nbextension install  --nbextensions=[PYPATH]/share/jupyter/nbextensions/`
[I 08:24:28 InstallContribNbextensionsApp] Installing [PYPATH]/lib/python3.6/site-packages/jupyter_highlight_selected_word-0.1.0-py3.6.egg/jupyter_highlight_selected_word/static/highlight_selected_word -> highlight_selected_word
[I 08:24:28 InstallContribNbextensionsApp] Copying: [PYPATH]/lib/python3.6/site-packages/jupyter_highlight_selected_word-0.1.0-py3.6.egg/jupyter_highlight_selected_word/static/highlight_selected_word -> [PYPATH]/share/jupyter/nbextensions/highlight_selected_word
Traceback (most recent call last):
  File "[PYPATH]/bin/jupyter-contrib", line 11, in <module>
    load_entry_point('jupyter-contrib-core==0.3.3', 'console_scripts', 'jupyter-contrib')()
  File "[PYPATH]/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "[PYPATH]/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "[PYPATH]/lib/python3.6/site-packages/jupyter_contrib_core-0.3.3-py3.6.egg/jupyter_contrib_core/application.py", line 50, in start
  File "[PYPATH]/lib/python3.6/site-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "[PYPATH]/lib/python3.6/site-packages/jupyter_contrib_nbextensions-0.4.0-py3.6.egg/jupyter_contrib_nbextensions/application.py", line 231, in start
    super(ContribNbextensionsApp, self).start()
  File "[PYPATH]/lib/python3.6/site-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "[PYPATH]/lib/python3.6/site-packages/jupyter_contrib_nbextensions-0.4.0-py3.6.egg/jupyter_contrib_nbextensions/application.py", line 178, in start
    toggle_install_files(self._toggle_value, **kwargs_files)
  File "[PYPATH]/lib/python3.6/site-packages/jupyter_contrib_nbextensions-0.4.0-py3.6.egg/jupyter_contrib_nbextensions/install.py", line 75, in toggle_install_files
    mod.__name__, overwrite=overwrite, symlink=symlink, **kwargs)
  File "[PYPATH]/lib/python3.6/site-packages/notebook/nbextensions.py", line 225, in install_nbextension_python
    destination=dest, logger=logger
  File "[PYPATH]/lib/python3.6/site-packages/notebook/nbextensions.py", line 199, in install_nbextension
    _maybe_copy(src, full_dest, logger=logger)
  File "[PYPATH]/lib/python3.6/site-packages/notebook/nbextensions.py", line 1046, in _maybe_copy
    shutil.copy2(src, dest)
  File "/usr/local/software/jureca/Stages/Devel-2017b/software/SciPy-Stack/2017b-gpsolf-2017b-Python-3.6.3/lib/python3.6/shutil.py", line 257, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/software/jureca/Stages/Devel-2017b/software/SciPy-Stack/2017b-gpsolf-2017b-Python-3.6.3/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
NotADirectoryError: [Errno 20] Not a directory: '[PYPATH]/lib/python3.6/site-packages/jupyter_highlight_selected_word-0.1.0-py3.6.egg/jupyter_highlight_selected_word/static/highlight_selected_word'
```

**Comment by jhgoebbert** [comment]
Hi,

sorry, my fault.
The file was accidentally created by my easybuild script.

Best,
Jens Henrik

**Comment by jcb91** [comment]
No worries, thanks for keeping this updated!

**Comment by jhgoebbert** [comment]
Hi, 

after some more examination I come to the conclusion ist is a bug in the setup routine of jupyter_contrib_nbextensions. The problem is, that jupyter_contrib_nbextensions should not assume, that the egg-file of  jupyter_highlight_selected_word is a directory.

New versions of setuptools seem not to be that conservitave anymore, when deciding if an egg shall be zipped or not (check http://setuptools.readthedocs.io/en/latest/setuptools.html#setting-the-zip-safe-flag).

But currently jupyter_contrib_nbextensions expects that jupyter_highlight_selected_word will NOT be zipped to a file but stays to be a directory. Assuming this, it tries to copy files on install into that directory, which is not garanteed to exist, but could also be an egg-file.

A solution could be to check, if an egg-path is really a directory and extract it, if it is an egg-file instead.

Best,
Jens Henrik

more details:
If a package contains only pure-Python code, it can stay as just an egg file. The Python interpreter can load the Python modules directly from the egg. If a package contains modules written in C or other data, then egg needs to be extracted so the C modules and/or data can be accessed.
