### ISSUE TITLE
Error loading server extension jupyter_nbextensions_configurator

### ISSUE THREAD

**Issue by motilaluom** [ipython-contrib/jupyter_contrib_nbextensions#1396]
I'm trying to install the extensions, after reading this [post ](https://towardsdatascience.com/bringing-the-best-out-of-jupyter-notebooks-for-data-science-f0871519ca29), however it seems not working as it should and I keep receiving  the following error:

`[I 23:18:51.011 NotebookApp] The port 8888 is already in use, trying another port.
[I 23:18:51.012 NotebookApp] The port 8889 is already in use, trying another port.
[I 23:18:51.013 NotebookApp] The port 8890 is already in use, trying another port.
[I 23:18:51.014 NotebookApp] The port 8891 is already in use, trying another port.
[I 23:18:51.015 NotebookApp] The port 8892 is already in use, trying another port.
[W 23:18:51.049 NotebookApp] Error loading server extension jupyter_nbextensions_configurator
Traceback (most recent call last):
File "C:\Users\moti.laluom\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 1572, in init_server_extensions
mod = importlib.import_module(modulename)
File "C:\Users\moti.laluom\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 994, in _gcd_import
File "", line 971, in _find_and_load
File "", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'jupyter_nbextensions_configurator'
[I 23:18:51.114 NotebookApp] JupyterLab beta preview extension loaded from C:\Users\moti.laluom\Anaconda3\lib\site-packages\jupyterlab
[I 23:18:51.115 NotebookApp] JupyterLab application directory is C:\Users\moti.laluom\Anaconda3\share\jupyter\lab
[I 23:18:51.120 NotebookApp] Serving notebooks from local directory: C:\Users\moti.laluom
[I 23:18:51.121 NotebookApp] The Jupyter Notebook is running at:
[I 23:18:51.121 NotebookApp] http://localhost:8936/?token=ee7f78008cd371fbc3ad7934946defab0fc7e89a04f1616f
[I 23:18:51.121 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 23:18:51.129 NotebookApp] 

To access the notebook, open this file in a browser:
file:///C:/Users/moti.laluom/AppData/Roaming/jupyter/runtime/nbserver-4592-open.html
Or copy and paste one of these URLs:
http://localhost:8936/?token=ee7f78008cd371fbc3ad7934946defab0fc7e89a04f1616f
[W 23:18:54.316 NotebookApp] 404 GET /nbextensions/nbextensions_configurator/tree_tab/main.js?v=20190209231850 (::1) 27.93ms referer=http://localhost:8936/tree
`
I read several issues here and on the web and came with nothing.
I'm not sure what's the problem and can I solve it

**Comment by Daya-Jin** [comment]
same question.
`
[W 17:10:11.686 LabApp] 加载插件 jupyter_nbextensions_configurator 失败
    Traceback (most recent call last):
      File "/home/hujinzhi/venv/lib/python3.6/site-packages/notebook/notebookapp.py", line 1655, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/home/hujinzhi/venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'jupyter_nbextensions_configurator'
[I 17:10:12.257 LabApp] JupyterLab extension loaded from /home/hujinzhi/venv/lib/python3.6/site-packages/jupyterlab
[I 17:10:12.257 LabApp] JupyterLab application directory is /home/hujinzhi/venv/share/jupyter/lab
[I 17:10:12.767 LabApp] 启动notebooks 在本地路径: /home/hujinzhi
[I 17:10:12.767 LabApp] 本程序运行在: http://user-ProLiant-ML350-Gen9:8910/
`

**Comment by darioromero** [comment]
I got the same problem: 
(gis) C:\Users\romeda\repos\endowment2019>jupyter notebook
[W 21:18:29.338 NotebookApp] Error loading server extension jupyter_nbextensions_configurator
    Traceback (most recent call last):
      File "c:\programdata\anaconda3\envs\gis\lib\site-packages\notebook\notebookapp.py", line 1655, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "c:\programdata\anaconda3\envs\gis\lib\importlib\__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'jupyter_nbextensions_configurator'
[I 21:18:29.503 NotebookApp] JupyterLab extension loaded from c:\programdata\anaconda3\envs\gis\lib\site-packages\jupyterlab
[I 21:18:29.503 NotebookApp] JupyterLab application directory is c:\programdata\anaconda3\envs\gis\share\jupyter\lab
[I 21:18:29.558 NotebookApp] Serving notebooks from local directory: C:\Users\romeda\repos\endowment2019
[I 21:18:29.558 NotebookApp] The Jupyter Notebook is running at:
[I 21:18:29.558 NotebookApp] http://localhost:8888/?token=27c3faf04e56da4835f91174c6640e035fdb021130e8f094
[I 21:18:29.558 NotebookApp]  or http://127.0.0.1:8888/?token=27c3faf04e56da4835f91174c6640e035fdb021130e8f094
[I 21:18:29.558 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 21:18:29.714 NotebookApp]

**Comment by ghuname** [comment]
I have the same problem as @darioromero.
Everything works but these errors are annoying.
