### ISSUE TITLE
JSON decoder error when loading extensions

### ISSUE THREAD

**Issue by Astrolumos** [ipython-contrib/jupyter_contrib_nbextensions#1404]
I install nbextensions without problem. But when I ran jupyter nbextensions_configurator enable I got:

Enabling: jupyter_nbextensions_configurator
- Writing config: /home/yanza15/.jupyter
    - Validating...
      jupyter_nbextensions_configurator 0.4.1 OK
Enabling notebook nbextension nbextensions_configurator/config_menu/main...
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbextensions_configurator", line 11, in <module>
    load_entry_point("jupyter-nbextensions-configurator==0.4.1", "console_scripts", "jupyter-nbextensions_configurator")()
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.5/dist-packages/jupyter_nbextensions_configurator/application.py", line 117, in start
    super(JupyterNbextensionsConfiguratorApp, self).start()
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/usr/local/lib/python3.5/dist-packages/jupyter_nbextensions_configurator/application.py", line 77, in start
    user=self.user, sys_prefix=self.sys_prefix)
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 351, in _set_nbextension_state
    cm.update(section, {"load_extensions": {require: state}})
  File "/usr/local/lib/python3.5/dist-packages/notebook/config_manager.py", line 134, in update
    data = self.get(section_name)
  File "/usr/local/lib/python3.5/dist-packages/notebook/config_manager.py", line 103, in get
    recursive_update(data, json.load(f))
  File "/usr/lib/python3.5/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 12 column 1 (char 154)

Can anyone help me?

**Comment by Astrolumos** [comment]
Update: I delete the ~/.jupyter folder and re-install jupyter and the problem is resolved. But I still don't know what causes it.
