### ISSUE TITLE
Jupyter totally broken after installing nb extension configurator

### ISSUE THREAD

**Issue by kaburelabs** [ipython-contrib/jupyter_contrib_nbextensions#1441]
Hi, I am facing a problem that broke my jupyter after trying to install nbextension-configurator with conda-forge.

My conda also was removed and I got many problems that even I tried to remove nbextension I keep having the same problem. 

The Jupyter are running but with this warnings on prompt and all my custom enviroments of my kernels is gone... Could someone help me please? 

I saw this problem in many issues but nothing worked to me. 

The problem: 
 [W 00:05:38.829 NotebookApp] Error loading server extension ipyparallel.nbextension
    Traceback (most recent call last):
      File "/home/leonardo/anaconda3/lib/python3.7/site-packages/notebook/notebookapp.py", line 1615, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/home/leonardo/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'ipyparallel'
[W 00:05:38.829 NotebookApp] Error loading server extension jupyterlab
    Traceback (most recent call last):
      File "/home/leonardo/anaconda3/lib/python3.7/site-packages/notebook/notebookapp.py", line 1615, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/home/leonardo/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'jupyterlab'
[W 00:05:38.829 NotebookApp] Error loading server extension nbextensions
    Traceback (most recent call last):
      File "/home/leonardo/anaconda3/lib/python3.7/site-packages/notebook/notebookapp.py", line 1615, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/home/leonardo/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'nbextensions'
[I 00:05:38.830 NotebookApp] Serving notebooks from local directory: /home/leonardo
[I 00:05:38.830 NotebookApp] The Jupyter Notebook is running at:
[I 00:05:38.830 NotebookApp] http://localhost:8888/?token=982763f675454460acfb7b70eec0070091df0076338eff27
[I 00:05:38.830 NotebookApp]  or http://127.0.0.1:8888/?token=982763f675454460acfb7b70eec0070091df0076338eff27
[I 00:05:38.830 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 00:05:38.845 NotebookApp] 

    To access the notebook, open this file in a browser:
        file:///run/user/1000/jupyter/nbserver-6243-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=982763f675454460acfb7b70eec0070091df0076338eff27
     or http://127.0.0.1:8888/?token=982763f675454460acfb7b70eec0070091df0076338eff27
[E 00:05:40.152 NotebookApp] Could not open static file ''
[W 00:05:40.177 NotebookApp] 404 GET /static/components/react/react-dom.production.min.js (127.0.0.1) 5.79ms referer=http://localhost:8888/tree?token=982763f675454460acfb7b70eec0070091df0076338eff27
[W 00:05:40.427 NotebookApp] 404 GET /static/components/react/react-dom.production.min.js (127.0.0.1) 1.08ms referer=http://localhost:8888/tree?token=982763f675454460acfb7b70eec0070091df0076338eff27
[W 00:05:40.703 NotebookApp] 404 GET /clusters?_=1565147140473 (127.0.0.1) 1.02ms referer=http://localhost:8888/tree

**Comment by gmseabra** [comment]
I confirm I'm having probably the same issue here. I'm using miniconda, and have just created a brand new env with the latest available versions of all packages. When I start the Jupyter notebook, I get:

``

**Comment by ChartPixel** [comment]
Exact problem here after installing nb-extension configurator for qviewer widget. Nothing worked to repair at first, no forced reinstall of jupyter, clean --all, etc.  Eventually solved it after some hours by:

1. pip install jinja2==3.0.3
2. pip install ipykernel --upgrade
3. pip install pyqt==5.12  (had to be downgraded)

After the above the "500 Internal Server Error" when opening a notebook disappeared, but some libraries dependent on tensorflow and  (e.g. spacy) didn't load properly.

4. pip install virtualenv --upgrade
5. pip uninstall protobuf
6. pip install nbconvert --upgrade
7. conda list tensorfor and make sure that both have the same version. I had to downgrate my tensorflow-estimator to 2.0.0. There was a conflic with google.protobuf.

I won't touch nb-ext configurator ever again :)
