### ISSUE TITLE
Install on ubuntu1804 failed

### ISSUE THREAD

**Issue by DawnEve** [ipython-contrib/jupyter_contrib_nbextensions#1507]
I use pip to install, but failed many times.

$ pip install jupyter_contrib_nbextensions -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com --user

```
Building wheels for collected packages: jupyter-latex-envs, jupyter-nbextensions-configurator
  Building wheel for jupyter-latex-envs (setup.py) ... **error**
  ERROR: Command errored out with exit status 1:
   command: /home/wangjl/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4z6s52ww/jupyter-latex-envs/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4z6s52ww/jupyter-latex-envs/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-gst537vr
       cwd: /tmp/pip-install-4z6s52ww/jupyter-latex-envs/
  Complete output (48 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/latex_envs
  copying src/latex_envs/__init__.py -> build/lib/latex_envs
  copying src/latex_envs/latex_envs.py -> build/lib/latex_envs
  running egg_info
  writing src/jupyter_latex_envs.egg-info/PKG-INFO
  writing dependency_links to src/jupyter_latex_envs.egg-info/dependency_links.txt
  writing entry points to src/jupyter_latex_envs.egg-info/entry_points.txt
  writing requirements to src/jupyter_latex_envs.egg-info/requires.txt
  writing top-level names to src/jupyter_latex_envs.egg-info/top_level.txt
  reading manifest file 'src/jupyter_latex_envs.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'src/jupyter_latex_envs.egg-info/SOURCES.txt'
  creating build/lib/latex_envs/static
  copying src/latex_envs/static/README.md -> build/lib/latex_envs/static
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-4z6s52ww/jupyter-latex-envs/setup.py", line 81, in <module>
      'Topic :: Utilities',
    File "/home/wangjl/anaconda3/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "/home/wangjl/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/wangjl/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/home/wangjl/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/wangjl/.local/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 202, in run
      self.run_command('build')
    File "/home/wangjl/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/wangjl/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/wangjl/anaconda3/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/wangjl/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/wangjl/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/wangjl/anaconda3/lib/python3.6/site-packages/setuptools/command/build_py.py", line 58, in run
      self.build_package_data()
    File "/home/wangjl/anaconda3/lib/python3.6/site-packages/setuptools/command/build_py.py", line 132, in build_package_data
      srcfile in self.distribution.convert_2to3_doctests):
  TypeError: argument of type 'NoneType' is not iterable
  ----------------------------------------
  ERROR: Failed building wheel for jupyter-latex-envs
```

**Comment by DawnEve** [comment]
I updated pip and setuptools, then it works.

```
pip install --upgrade pip
pip install -U setuptools -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com
```
