### ISSUE TITLE
Error loading server extension jupyter_nbextensions_configurator

### ISSUE THREAD

**Issue by fanicey** [ipython-contrib/jupyter_contrib_nbextensions#1513]
Hi,
I followed the instructions to install jupyter-contrib-nbextensions. However, when I launch jupyter notebook, I got the following ERROR:

Error loading server extension jupyter_nbextensions_configurator
    Traceback (most recent call last):                                                       
      File "/apps/usr/local64/anaconda-appfraud/lib/python3.6/site-packages/notebook/notebookapp.py", line 1451, in init_server_extensions
        mod = importlib.import_module(modulename)                                                                                         
      File "/apps/usr/local64/anaconda-appfraud/lib/python3.6/importlib/__init__.py", line 126, in import_module                          
        return _bootstrap._gcd_import(name[level:], package, level)                                                                       
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import                                                                      
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load                                                                   
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked                                                          
    ModuleNotFoundError: No module named 'jupyter_nbextensions_configurator'

I then tried the solution to a previous similar issues, however, it does not work. I also tried to create a new environment without jupyter-contrib-nbextensions, but again, when I launch jupyter notebook, I got the same error message. 

> I had sort of a traumatic past installing jupyter-contrib-nbextensions

Oh dear, sorry to hear it was problematic!

> Maybe a file got damaged while installing and uninstalling several times?

It looks as though you've inadvertently enabled a non-existent serverextension called `nbextensions`. This could be in one of several config files - see http://jupyter-contrib-nbextensions.readthedocs.io/en/latest/config.html for details of jupyter config files.

To find out which, you can use 

    jupyter serverextension list

To fix, you should be able to disable it using one of the commands

    jupyter serverextension disable nbextensions
    jupyter serverextension disable nbextensions --user
    jupyter serverextension disable nbextensions --sys-prefix

Depending on which file it's been configured in. You can safely disable it in all (system, user & sys-prefix) config files by running each command, though.

Hope that makes sense 😄

_Originally posted by @jcb91 in https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/1077#issuecomment-326768537_

**Comment by fanicey** [comment]
Followup: I manually changed the file .jupyter/jupyter_notebook_config.json and set jupyter_nbextensions_configurator to false. Then I don't see this ERROR when launching notebook.

However, I still cannot import any module. I have the package pomegranate installed, but when I tried to import, it shows:
    ---------------------------------------------------------------------------
    ModuleNotFoundError                       Traceback (most recent call last)
    <ipython-input-3-1cb5711ea5a2> in <module>()
    ----> 1 from pomegranate import *
             2 import time
             3 import pandas as pd
             4  import numpy as np
             5 import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'pomegranate'

Before installing jupyter-contrib-nbextensions everything worked fine. All the problems happened after I tried to install it. I don't have a clue on how to solve it. Any advice? Thanks!
