### ISSUE TITLE
ModuleNotFoundError: No module named 'jupytext'

### ISSUE THREAD

**Issue by schuhegger** [ipython-contrib/jupyter_contrib_nbextensions#1543]
I have tried a lot of different things and unfortunately I do not understand what my problem causes. I removed and installed jupytext several times in different ways but I could not fix this issue on my own. 
If I want to run "jupyter notebook" the jupytext extension is not available in the notebooks and I get an error: 

(plightning3):~/Documents/$ jupyter notebook
[W 18:47:44.872 NotebookApp] Error loading server extension jupytext
    Traceback (most recent call last):
      File "/home/.local/lib/python3.8/site-packages/notebook/notebookapp.py", line 1942, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'jupytext'

If I run " jupyter serverextension list" I get the following: 
(plightning3):~/Documents/Code/s429r$ jupyter serverextension list
config dir: /home/AD/s429r/.jupyter
    jupytext  enabled 
    - Validating...
Error loading server extension jupytext
      X is jupytext importable?

If I just run jupytext without any further command, I get: 
Traceback (most recent call last):
  File "/home/anaconda3/envs/plightning3/bin/jupytext", line 10, in <module>
    sys.exit(jupytext())
  File "/home/anaconda3/envs/plightning3/lib/python3.8/site-packages/jupytext/cli.py", line 356, in jupytext
    raise ValueError(
ValueError: Please provide one of --to, --output, --set-formats, --sync, --pipe, --check, --update-metadata, --format-options, --set-kernel or --execute

Versions: 
python=3.8.6
jupytext=1.7.1

**Comment by schuhegger** [comment]
Unfortunately, opened issue at wrong place
