### ISSUE TITLE
PermissionError: [Errno 13] Permission denied:

### ISSUE THREAD

**Issue by akitxu** [ipython-contrib/jupyter_contrib_nbextensions#1554]
I have installed Anaconda 3. I try to install TOC and it returns the error
`(base) enri@enri-260-p100ns:~$ jupyter labextension install @jupyterlab/toc
An error occured.
PermissionError: [Errno 13] Permission denied: '/home/enri/anaconda3/share/jupyter/lab/extensions'
See the log file for details:  /tmp/jupyterlab-debug-_svq1n2o.log
` 
The .log file is
`Node v15.8.0

Yarn configuration loaded.
Traceback (most recent call last):

  File "/home/enri/anaconda3/lib/python3.8/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/home/enri/anaconda3/lib/python3.8/site-packages/jupyterlab/labextensions.py", line 93, in start
    ans = self.run_task()

  File "/home/enri/anaconda3/lib/python3.8/site-packages/jupyterlab/labextensions.py", line 138, in run_task
    return any([

  File "/home/enri/anaconda3/lib/python3.8/site-packages/jupyterlab/labextensions.py", line 139, in <listcomp>
    install_extension(

  File "/home/enri/anaconda3/lib/python3.8/site-packages/jupyterlab/commands.py", line 388, in install_extension
    return handler.install_extension(extension, pin=pin)

  File "/home/enri/anaconda3/lib/python3.8/site-packages/jupyterlab/commands.py", line 599, in install_extension
    self._ensure_app_dirs()

  File "/home/enri/anaconda3/lib/python3.8/site-packages/jupyterlab/commands.py", line 1393, in _ensure_app_dirs
    os.makedirs(path)

  File "/home/enri/anaconda3/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)

PermissionError: [Errno 13] Permission denied: '/home/enri/anaconda3/share/jupyter/lab/extensions'

Exiting application: jupyter`

How should I go about giving that permission? I will appreciate help.

**Comment by akitxu** [comment]
LO he resuelto haciendo  `sudo chown -R enri:enri /home/enri/anaconda3`. Gracias
