### ISSUE TITLE
install nbextensions in \site-packages\jupyter_contrib_nbextensions

### ISSUE THREAD

**Issue by LeeTian** [ipython-contrib/jupyter_contrib_nbextensions#1645]
I wan't to use pyecharts , but pyecharts can't show on jupyter notebook , becase jupyter notebook can't load pyecharts's css & js files(https://github.com/pyecharts/pyecharts-assets).
so I will install nbextensions like this https://aitechtogether.com/python/52523.html

pip install -i http://pypi.douban.com/simple --trusted-host pypi.douban.com jupyter_contrib_nbextensions
C:\Users\he\Python\Python38\Lib\site-packages\jupyter_contrib_nbextensions
python application.py install

and here is more error:

```
Traceback (most recent call last):
  File "D:\Program Files\lang\python\310\lib\site-packages\jupyter_contrib_core\notebook_compat\nbextensions.py", line 6, in <module>
    from notebook.extensions import BaseExtensionApp
ModuleNotFoundError: No module named 'notebook.extensions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\lang\python\310\lib\site-packages\jupyter_contrib_core\notebook_compat\nbextensions.py", line 10, in <module>
    from notebook.nbextensions import BaseNBExtensionApp
ModuleNotFoundError: No module named 'notebook.nbextensions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\lang\python\310\Lib\site-packages\jupyter_contrib_nbextensions\application.py", line 7, in <module>
    from jupyter_contrib_core.notebook_compat.nbextensions import ArgumentConflict
  File "D:\Program Files\lang\python\310\lib\site-packages\jupyter_contrib_core\notebook_compat\nbextensions.py", line 12, in <module>
    from ._compat.nbextensions import BaseNBExtensionApp
  File "D:\Program Files\lang\python\310\lib\site-packages\jupyter_contrib_core\notebook_compat\_compat\nbextensions.py", line 35, in <module>
    from notebook.nbextensions import (
ModuleNotFoundError: No module named 'notebook.nbextensions'
``` 

anybody help me 

thank you very much !

Tyler
2023/7/22

**Comment by MMCMA** [comment]
I experience the same error it seems the most recent version of notebook (7.0.0 / July 19th) is not compatible, fixing `notebook=6.5.4` fixes the problem for now. Someone still needs to fix this bug.
