### ISSUE TITLE
nbextensions conda installation problem

### ISSUE THREAD

**Issue by samk1404** [ipython-contrib/jupyter_contrib_nbextensions#1656]
I tried to install nbextensions using conda :
`conda install -c conda-forge jupyter_contrib_nbextensions`
Got this error message:
`(greentea) PS C:\Users\samk1> conda install -c conda-forge jupyter_contrib_nbextensions
Channels:
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\samk1\Conda\miniconda3\envs\greentea

  added / updated specs:
    - jupyter_contrib_nbextensions

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libxml2-2.11.6             |       hc3477c8_0         1.6 MB  conda-forge
    libxslt-1.1.37             |       h6070c61_1         407 KB  conda-forge
    lxml-4.9.3                 |  py310h46d54dd_3         992 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         2.9 MB

The following NEW packages will be INSTALLED:

  ipython_genutils   conda-forge/noarch::ipython_genutils-0.2.0-py_1
  jupyter_contrib_c~ conda-forge/noarch::jupyter_contrib_core-0.4.0-pyhd8ed1ab_0
  jupyter_contrib_n~ conda-forge/noarch::jupyter_contrib_nbextensions-0.7.0-pyhd8ed1ab_0
  jupyter_highlight~ conda-forge/win-64::jupyter_highlight_selected_word-0.2.0-py310h5588dad_1005
  jupyter_latex_envs conda-forge/noarch::jupyter_latex_envs-1.4.6-pyhd8ed1ab_1002
  jupyter_nbextensi~ conda-forge/noarch::jupyter_nbextensions_configurator-0.6.1-pyhd8ed1ab_0
  libiconv           conda-forge/win-64::libiconv-1.17-hcfcfb64_2
  libxml2            conda-forge/win-64::libxml2-2.11.6-hc3477c8_0
  libxslt            conda-forge/win-64::libxslt-1.1.37-h6070c61_1
  lxml               conda-forge/win-64::lxml-4.9.3-py310h46d54dd_3

Proceed ([y]/n)? y

Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: - Traceback (most recent call last):
  File "C:\Users\samk1\Conda\miniconda3\envs\greentea\lib\site-packages\jupyter_contrib_core\notebook_compat\nbextensions.py", line >    from notebook.extensions import BaseExtensionApp
ModuleNotFoundError: No module named 'notebook.extensions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\samk1\Conda\miniconda3\envs\greentea\lib\site-packages\jupyter_contrib_core\notebook_compat\nbextensions.py", line >    from notebook.nbextensions import BaseNBExtensionApp
ModuleNotFoundError: No module named 'notebook.nbextensions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\samk1\Conda\miniconda3\envs\greentea\lib\site-packages\jupyter_contrib_core\notebook_compat\nbextensions.py", line >    from ._compat.nbextensions import BaseNBExtensionApp
  File "C:\Users\samk1\Conda\miniconda3\envs\greentea\lib\site-packages\jupyter_contrib_core\notebook_compat\_compat\nbextensions.py>    from notebook.nbextensions import (
ModuleNotFoundError: No module named 'notebook.nbextensions'

done
ERROR conda.core.link:_execute(945): An error occurred while installing package 'conda-forge::jupyter_highlight_selected_word-0.2.0-.Rolling back transaction: done

LinkError: post-link script failed for package conda-forge::jupyter_highlight_selected_word-0.2.0-py310h5588dad_1005
location of failed script: C:\Users\samk1\Conda\miniconda3\envs\greentea\Scripts\.jupyter_highlight_selected_word-post-link.bat
==> script messages <==
Traceback (most recent call last):
  File "C:\Users\samk1\Conda\miniconda3\envs\greentea\lib\site-packages\jupyter_contrib_core\notebook_compat\nbextensions.py", line >    from notebook.extensions import BaseExtensionApp
ModuleNotFoundError: No module named 'notebook.extensions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\samk1\Conda\miniconda3\envs\greentea\lib\site-packages\jupyter_contrib_core\notebook_compat\nbextensions.py", line >    from notebook.nbextensions import BaseNBExtensionApp
ModuleNotFoundError: No module named 'notebook.nbextensions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\samk1\Conda\miniconda3\envs\greentea\lib\site-packages\jupyter_contrib_core\notebook_compat\nbextensions.py", line >    from ._compat.nbextensions import BaseNBExtensionApp
  File "C:\Users\samk1\Conda\miniconda3\envs\greentea\lib\site-packages\jupyter_contrib_core\notebook_compat\_compat\nbextensions.py>    from notebook.nbextensions import (
ModuleNotFoundError: No module named 'notebook.nbextensions'

==> script output <==
stdout:
stderr:
return code: 1

()`

also these are the versions of jupyter:
`IPython          : 8.19.0
ipykernel        : 6.26.0
ipywidgets       : 8.1.1
jupyter_client   : 8.6.0
jupyter_core     : 5.5.1
jupyter_server   : 2.12.1
jupyterlab       : 4.0.9
nbclient         : 0.8.0
nbconvert        : 7.13.1
nbformat         : 5.9.2
notebook         : 7.0.6
qtconsole        : 5.5.1
traitlets        : 5.14.0`
How to fix this?

**Comment by smsnunte** [comment]
Hi, I have the same issue, have you found a solution yet?
