### ISSUE TITLE
Incompatible with Jupyter Notebook v7.0.6

### ISSUE THREAD

**Issue by alanmaulanaa** [ipython-contrib/jupyter_contrib_nbextensions#1661]
There's some problem while install this in this current version of Jupyter Notebook.

1. The pip install step is fine.
This is error when try to install
`C:\Users\ALAN>jupyter contrib nbextension install --sys-prefix
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ALAN\AppData\Local\Programs\Python\Python311\Scripts\jupyter-contrib.EXE\__main__.py", line 7, in <module>
  File "C:\Users\ALAN\AppData\Local\Programs\Python\Python311\Lib\site-packages\jupyter_core\application.py", line 283, in launch_instance
    super().launch_instance(argv=argv, **kwargs)
  File "C:\Users\ALAN\AppData\Local\Programs\Python\Python311\Lib\site-packages\traitlets\config\application.py", line 1073, in launch_instance
    app = cls.instance(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ALAN\AppData\Local\Programs\Python\Python311\Lib\site-packages\traitlets\config\configurable.py", line 583, in instance
    inst = cls(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ALAN\AppData\Local\Programs\Python\Python311\Lib\site-packages\jupyter_contrib_core\application.py", line 27, in __init__
    self._refresh_subcommands()
  File "C:\Users\ALAN\AppData\Local\Programs\Python\Python311\Lib\site-packages\jupyter_contrib_core\application.py", line 43, in _refresh_subcommands
    get_subcommands_dict = entrypoint.load()
                           ^^^^^^^^^^^^^^^^^
  File "C:\Users\ALAN\AppData\Local\Programs\Python\Python311\Lib\site-packages\pkg_resources\__init__.py", line 2471, in load
    return self.resolve()
           ^^^^^^^^^^^^^^
  File "C:\Users\ALAN\AppData\Local\Programs\Python\Python311\Lib\site-packages\pkg_resources\__init__.py", line 2477, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ALAN\AppData\Local\Programs\Python\Python311\Lib\site-packages\jupyter_contrib_nbextensions\__init__.py", line 5, in <module>
    import jupyter_nbextensions_configurator
  File "C:\Users\ALAN\AppData\Local\Programs\Python\Python311\Lib\site-packages\jupyter_nbextensions_configurator\__init__.py", line 18, in <module>
    from notebook.base.handlers import APIHandler, IPythonHandler
ModuleNotFoundError: No module named 'notebook.base'`

2. Also with enable step

`C:\Users\ALAN>jupyter nbextensions_configurator enable --user  # can be skipped for notebook >=5.3
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ALAN\AppData\Local\Programs\Python\Python311\Scripts\jupyter-nbextensions_configurator.EXE\__main__.py", line 4, in <module>
  File "C:\Users\ALAN\AppData\Local\Programs\Python\Python311\Lib\site-packages\jupyter_nbextensions_configurator\__init__.py", line 18, in <module>
    from notebook.base.handlers import APIHandler, IPythonHandler
ModuleNotFoundError: No module named 'notebook.base'`

**Comment by JustToFaith** [comment]
I have the same problem

**Comment by auriz24** [comment]
Jupyter Notebook v7 is based on JupyterLab, which makes it fundamentally different from Notebook v6. So, these notebook extensions here don't work on Notebook v7 anymore. 

More details: https://jupyter.org/enhancement-proposals/79-notebook-v7/notebook-v7.html#extensions

Some of these extensions have alternatives for JupyterLab: https://jupyterlab-contrib.github.io/migrate_from_classical.html

I'm trying to migrate to Notebook v7, and I'm struggling with it. I'm missing some of the extensions there, or they don't work in the same way as they did in the classic notebook (v6, 5, ...). But I also don't have experience to update / adjust those extensions myself.

**Comment by tanhaow** [comment]
same problem here
