### ISSUE TITLE
Pymarkdown broke the command line pdf generation (pdf generation from live web session works but it does not interpret the pymarkdown code) 

### ISSUE THREAD

**Issue by erichu8** [ipython-contrib/jupyter_contrib_nbextensions#723]
Since I installed the pymarkdown extension I can't run nbconverter --to pdf file.ipynb without getting an error. Error is consistently replicated on every fresh conda-forge linux64 environments

**Comment by juhasch** [comment]
It this the error you get ?
https://github.com/jupyter/nbconvert/issues/362

**Comment by erichu8** [comment]
Making the two strings raw allows me to generate a PDF now. Is this a bug in all ubuntu16 conda-forge installation or it was only my machines?

Also there are a number of exceptions now raised while parsing the json config file; is it normal?

```
[NbConvertApp] ERROR | Exception while loading config file /anaconda/etc/jupyter/jupyter_nbconvert_config.json
Traceback (most recent call last):
  File "/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 534, in _load_config_files
    config = loader.load_config()
  File "/anaconda/lib/python2.7/site-packages/traitlets/config/loader.py", line 406, in load_config
    dct = self._read_file_as_dict()
  File "/anaconda/lib/python2.7/site-packages/traitlets/config/loader.py", line 412, in _read_file_as_dict
    return json.load(f)
  File "/anaconda/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/anaconda/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/anaconda/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/anaconda/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[NbConvertApp] Looking for jupyter_nbconvert_config in /Users/eric/.jupyter
[NbConvertApp] ERROR | Exception while loading config file /Users/eric/.jupyter/jupyter_nbconvert_config.json
Traceback (most recent call last):
  File "/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 534, in _load_config_files
    config = loader.load_config()
  File "/anaconda/lib/python2.7/site-packages/traitlets/config/loader.py", line 406, in load_config
    dct = self._read_file_as_dict()
  File "/anaconda/lib/python2.7/site-packages/traitlets/config/loader.py", line 412, in _read_file_as_dict
    return json.load(f)
  File "/anaconda/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/anaconda/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/anaconda/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/anaconda/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by juhasch** [comment]
Good question. I have similar problems, but only on my Linux machine.

**Comment by erichu8** [comment]
I have other few machines (win7 & macs) would you like me to try the replicability there too? I could do it early next week..

**Comment by juhasch** [comment]
Can you try the fix here:
https://github.com/ipython/ipython_genutils/pull/8

**Comment by jcb91** [comment]
@erichu8 did you get this resolved in the end?
