### ISSUE TITLE
Nosetest failing on MacOS

### ISSUE THREAD

**Issue by juhasch** [ipython-contrib/jupyter_contrib_nbextensions#760]
Works fine on Linux, on MacOS I get this with current master:

```
...............Command "/Users/juhasch/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/var/folders/ch/yvjnrr5j62b6b5lsvgctsrk40000gn/T/pip-veup003i-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/ch/yvjnrr5j62b6b5lsvgctsrk40000gn/T/pip-ssgjxr31-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /var/folders/ch/yvjnrr5j62b6b5lsvgctsrk40000gn/T/pip-veup003i-build/
FCommand "/Users/juhasch/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/var/folders/ch/yvjnrr5j62b6b5lsvgctsrk40000gn/T/pip-q2zm_7j0-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/ch/yvjnrr5j62b6b5lsvgctsrk40000gn/T/pip-bz8g5gvk-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /var/folders/ch/yvjnrr5j62b6b5lsvgctsrk40000gn/T/pip-q2zm_7j0-build/
F......
======================================================================
FAIL: Check migrate script removes old install correctly.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/juhasch/git/jupyter_contrib_nbextensions/tests/test_migrate.py", line 142, in test_01_migrate_main
    installed_files = self.install_old_pkg()
  File "/Users/juhasch/git/jupyter_contrib_nbextensions/tests/test_migrate.py", line 72, in install_old_pkg
    'pip should list {} as installed'.format(old_pkg_project_name))
AssertionError: 'Python-contrib-nbextensions' not found in ['jupyter-contrib-nbextensions', 'PhysicalQuantities', 'wrapt', 'Sphinx', 'vispy', 'spectrum', 'easydev', 'alabaster', 'altair', 'anaconda-client', 'anaconda-navigator', 'appnope', 'argcomplete', 'astroid', 'astropy', 'Babel', 'backports.shutil-get-terminal-size', 'beautifulsoup4', 'bitarray', 'blaze', 'bokeh', 'boto', 'Bottleneck', 'certifi', 'cffi', 'chest', 'click', 'cloudpickle', 'clyent', 'colorama', 'CommonMark', 'conda', 'conda-build', 'conda-env', 'conda-manager', 'configobj', 'contextlib2', 'cryptography', 'cycler', 'Cython', 'cytoolz', 'dask', 'datashape', 'decorator', 'dill', 'docutils', 'dynd', 'et-xmlfile', 'fastcache', 'Flask', 'Flask-Cors', 'gevent', 'graphviz', 'greenlet', 'h5py', 'HeapDict', 'idna', 'imagesize', 'ipykernel', 'ipython', 'ipython-genutils', 'ipywidgets', 'itsdangerous', 'jdcal', 'jedi', 'Jinja2', 'jsonschema', 'jupyter', 'jupyter-client', 'jupyter-console', 'jupyter-contrib-core', 'jupyter-core', 'jupyter-nbextensions-configurator', 'jupyterlab', 'lazy-object-proxy', 'line-profiler', 'llvmlite', 'locket', 'logilab-common', 'lxml', 'MarkupSafe', 'matlab-kernel', 'matplotlib', 'metakernel', 'mistune', 'mpmath', 'multipledispatch', 'nb-anacondacloud', 'nb-conda', 'nb-conda-kernels', 'nbconvert', 'nbformat', 'nbpresent', 'networkx', 'nltk', 'nose', 'notebook', 'numba', 'numexpr', 'numpy', 'odo', 'openpyxl', 'paho-mqtt', 'pandas', 'pandoc', 'parse', 'partd', 'path.py', 'pathlib2', 'patsy', 'pep8', 'pexpect', 'pickleshare', 'Pillow', 'pip', 'ply', 'psutil', 'ptyprocess', 'py', 'pyasn1', 'pycosat', 'pycparser', 'pycrypto', 'pycurl', 'pyflakes', 'Pygments', 'pylint', 'pymatbridge', 'pyOpenSSL', 'pypandoc', 'PyParse', 'pyparsing', 'pyqtgraph', 'pytest', 'python-dateutil', 'pytz', 'PyVISA', 'PyVISA-sim', 'PyYAML', 'pyzmq', 'QtAwesome', 'qtconsole', 'QtPy', 'recommonmark', 'redis', 'requests', 'rope-py3k', 'ruamel-yaml', 'scikit-image', 'scikit-learn', 'scipy', 'setuptools', 'simplegeneric', 'singledispatch', 'six', 'snowballstemmer', 'sockjs-tornado', 'sortedcontainers', 'sphinx-rtd-theme', 'spyder', 'SQLAlchemy', 'statsmodels', 'stringparser', 'sympy', 'tables', 'terminado', 'toolz', 'tornado', 'traitlets', 'unicodecsv', 'vega', 'Werkzeug', 'wheel', 'xarray', 'xlrd', 'XlsxWriter', 'xlwings', 'xlwt', 'appscript', 'scikit-rf'] : pip should list Python-contrib-nbextensions as installed
-------------------- >> begin captured stdout << ---------------------
Collecting https://github.com/ipython-contrib/IPython-notebook-extensions/archive/c6d65e7826657a23c47b1fadbf8557a06e774db2.zip
  Looking up "https://github.com/ipython-contrib/IPython-notebook-extensions/archive/c6d65e7826657a23c47b1fadbf8557a06e774db2.zip" in the cache
  Returning cached "301 Moved Permanently" response (ignoring date and etag information)
  Looking up "https://github.com/ipython-contrib/jupyter_contrib_nbextensions/archive/c6d65e7826657a23c47b1fadbf8557a06e774db2.zip" in the cache
  No cache entry available
  Starting new HTTPS connection (1): github.com
  "GET /ipython-contrib/jupyter_contrib_nbextensions/archive/c6d65e7826657a23c47b1fadbf8557a06e774db2.zip HTTP/1.1" 302 None
  Looking up "https://codeload.github.com/ipython-contrib/jupyter_contrib_nbextensions/zip/c6d65e7826657a23c47b1fadbf8557a06e774db2" in the cache
  Current age based on date: 242
  Starting new HTTPS connection (1): codeload.github.com
  "GET /ipython-contrib/jupyter_contrib_nbextensions/zip/c6d65e7826657a23c47b1fadbf8557a06e774db2 HTTP/1.1" 200 12829407
  Downloading https://github.com/ipython-contrib/IPython-notebook-extensions/archive/c6d65e7826657a23c47b1fadbf8557a06e774db2.zip (12.8MB)
  Downloading from URL https://github.com/ipython-contrib/IPython-notebook-extensions/archive/c6d65e7826657a23c47b1fadbf8557a06e774db2.zip
  Updating cache with response from "https://codeload.github.com/ipython-contrib/jupyter_contrib_nbextensions/zip/c6d65e7826657a23c47b1fadbf8557a06e774db2"
  Caching due to etag
  Running setup.py (path:/var/folders/ch/yvjnrr5j62b6b5lsvgctsrk40000gn/T/pip-veup003i-build/setup.py) egg_info for package from https://github.com/ipython-contrib/IPython-notebook-extensions/archive/c6d65e7826657a23c47b1fadbf8557a06e774db2.zip
    Running command python setup.py egg_info

    *********************************************************************************************************
    IPython-contrib-nbextensions - (C) 2013-2016, IPython-contrib Developers - All rights reserved.

    contains a collection of extensions that add functionality to the Jupyter notebook. These extensions are
    mostly written in Javascript and will be loaded locally in your Browser.

    The IPython-contrib repository https://github.com/ipython-contrib/IPython-notebook-extensions
    is maintained independently by a group of users and developers and not officially related to the
    IPython development team.

    The maturity of the provided extensions may vary, please create an issue if you encounter any problems.

    Released under Modified BSD License, read COPYING file for more details.
    *********************************************************************************************************

    running egg_info
    creating pip-egg-info/Python_contrib_nbextensions.egg-info
    writing dependency_links to pip-egg-info/Python_contrib_nbextensions.egg-info/dependency_links.txt
    writing requirements to pip-egg-info/Python_contrib_nbextensions.egg-info/requires.txt
    writing top-level names to pip-egg-info/Python_contrib_nbextensions.egg-info/top_level.txt
    writing pip-egg-info/Python_contrib_nbextensions.egg-info/PKG-INFO
    writing manifest file 'pip-egg-info/Python_contrib_nbextensions.egg-info/SOURCES.txt'
    /Users/juhasch/anaconda3/lib/python3.5/site-packages/setuptools/dist.py:373: UserWarning: The version specified ('alpha') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
      "details." % self.metadata.version
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'pip-egg-info/Python_contrib_nbextensions.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/Python_contrib_nbextensions.egg-info/SOURCES.txt'
  Source in /var/folders/ch/yvjnrr5j62b6b5lsvgctsrk40000gn/T/pip-veup003i-build has version alpha, which satisfies requirement Python-contrib-nbextensions===alpha from https://github.com/ipython-contrib/IPython-notebook-extensions/archive/c6d65e7826657a23c47b1fadbf8557a06e774db2.zip
Requirement already satisfied (use --upgrade to upgrade): jupyter_core in /Users/juhasch/anaconda3/lib/python3.5/site-packages (from Python-contrib-nbextensions===alpha)
Requirement already satisfied (use --upgrade to upgrade): jupyter_nbextensions_configurator in /Users/juhasch/anaconda3/lib/python3.5/site-packages (from Python-contrib-nbextensions===alpha)
Requirement already satisfied (use --upgrade to upgrade): nbconvert in /Users/juhasch/anaconda3/lib/python3.5/site-packages (from Python-contrib-nbextensions===alpha)
Requirement already satisfied (use --upgrade to upgrade): notebook in /Users/juhasch/anaconda3/lib/python3.5/site-packages (from Python-contrib-nbextensions===alpha)
Requirement already satisfied (use --upgrade to upgrade): psutil>=2.2.1 in /Users/juhasch/anaconda3/lib/python3.5/site-packages (from Python-contrib-nbextensions===alpha)
Requirement already satisfied (use --upgrade to upgrade): pyyaml in /Users/juhasch/anaconda3/lib/python3.5/site-packages (from Python-contrib-nbextensions===alpha)
Requirement already satisfied (use --upgrade to upgrade): tornado in /Users/juhasch/anaconda3/lib/python3.5/site-packages (from Python-contrib-nbextensions===alpha)
Requirement already satisfied (use --upgrade to upgrade): traitlets in /Users/juhasch/anaconda3/lib/python3.5/site-packages (from Python-contrib-nbextensions===alpha)
Could not parse version from link: https://github.com/ipython-contrib/IPython-notebook-extensions/archive/c6d65e7826657a23c47b1fadbf8557a06e774db2.zip
Installing collected packages: Python-contrib-nbextensions
  Running setup.py install for Python-contrib-nbextensions: started
    Running command /Users/juhasch/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/var/folders/ch/yvjnrr5j62b6b5lsvgctsrk40000gn/T/pip-veup003i-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/ch/yvjnrr5j62b6b5lsvgctsrk40000gn/T/pip-ssgjxr31-record/install-record.txt --single-version-externally-managed --compile
    Running source install...
    Extensions and templates path: /var/folders/ch/yvjnrr5j62b6b5lsvgctsrk40000gn/T/jupyter_8elqbpsy/env_vars/data
    Installing Jupyter notebook extensions.
    Done!
    Configuring extensions...
    Cannot configure while the Jupyter notebook server is running
    Running setup.py install for Python-contrib-nbextensions: finished with status 'error'
Cleaning up...
  Removing source in /var/folders/ch/yvjnrr5j62b6b5lsvgctsrk40000gn/T/pip-veup003i-build
Exception information:
Traceback (most recent call last):
  File "/Users/juhasch/anaconda3/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Users/juhasch/anaconda3/lib/python3.5/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Users/juhasch/anaconda3/lib/python3.5/site-packages/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/Users/juhasch/anaconda3/lib/python3.5/site-packages/pip/req/req_install.py", line 880, in install
    spinner=spinner,
  File "/Users/juhasch/anaconda3/lib/python3.5/site-packages/pip/utils/__init__.py", line 718, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "/Users/juhasch/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/var/folders/ch/yvjnrr5j62b6b5lsvgctsrk40000gn/T/pip-veup003i-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/ch/yvjnrr5j62b6b5lsvgctsrk40000gn/T/pip-ssgjxr31-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /var/folders/ch/yvjnrr5j62b6b5lsvgctsrk40000gn/T/pip-veup003i-build/

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
pip.vcs: DEBUG: Registered VCS backend: git
pip.vcs: DEBUG: Registered VCS backend: hg
pip.vcs: DEBUG: Registered VCS backend: svn
pip.vcs: DEBUG: Registered VCS backend: bzr
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: Check migrate application removes old install correctly.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/juhasch/git/jupyter_contrib_nbextensions/tests/test_migrate.py", line 149, in test_02_migrate_app
    installed_files = self.install_old_pkg()
  File "/Users/juhasch/git/jupyter_contrib_nbextensions/tests/test_migrate.py", line 72, in install_old_pkg
    'pip should list {} as installed'.format(old_pkg_project_name))
AssertionError: 'Python-contrib-nbextensions' not found in ['jupyter-contrib-nbextensions', 'PhysicalQuantities', 'wrapt', 'Sphinx', 'vispy', 'spectrum', 'easydev', 'alabaster', 'altair', 'anaconda-client', 'anaconda-navigator', 'appnope', 'argcomplete', 'astroid', 'astropy', 'Babel', 'backports.shutil-get-terminal-size', 'beautifulsoup4', 'bitarray', 'blaze', 'bokeh', 'boto', 'Bottleneck', 'certifi', 'cffi', 'chest', 'click', 'cloudpickle', 'clyent', 'colorama', 'CommonMark', 'conda', 'conda-build', 'conda-env', 'conda-manager', 'configobj', 'contextlib2', 'cryptography', 'cycler', 'Cython', 'cytoolz', 'dask', 'datashape', 'decorator', 'dill', 'docutils', 'dynd', 'et-xmlfile', 'fastcache', 'Flask', 'Flask-Cors', 'gevent', 'graphviz', 'greenlet', 'h5py', 'HeapDict', 'idna', 'imagesize', 'ipykernel', 'ipython', 'ipython-genutils', 'ipywidgets', 'itsdangerous', 'jdcal', 'jedi', 'Jinja2', 'jsonschema', 'jupyter', 'jupyter-client', 'jupyter-console', 'jupyter-contrib-core', 'jupyter-core', 'jupyter-nbextensions-configurator', 'jupyterlab', 'lazy-object-proxy', 'line-profiler', 'llvmlite', 'locket', 'logilab-common', 'lxml', 'MarkupSafe', 'matlab-kernel', 'matplotlib', 'metakernel', 'mistune', 'mpmath', 'multipledispatch', 'nb-anacondacloud', 'nb-conda', 'nb-conda-kernels', 'nbconvert', 'nbformat', 'nbpresent', 'networkx', 'nltk', 'nose', 'notebook', 'numba', 'numexpr', 'numpy', 'odo', 'openpyxl', 'paho-mqtt', 'pandas', 'pandoc', 'parse', 'partd', 'path.py', 'pathlib2', 'patsy', 'pep8', 'pexpect', 'pickleshare', 'Pillow', 'pip', 'ply', 'psutil', 'ptyprocess', 'py', 'pyasn1', 'pycosat', 'pycparser', 'pycrypto', 'pycurl', 'pyflakes', 'Pygments', 'pylint', 'pymatbridge', 'pyOpenSSL', 'pypandoc', 'PyParse', 'pyparsing', 'pyqtgraph', 'pytest', 'python-dateutil', 'pytz', 'PyVISA', 'PyVISA-sim', 'PyYAML', 'pyzmq', 'QtAwesome', 'qtconsole', 'QtPy', 'recommonmark', 'redis', 'requests', 'rope-py3k', 'ruamel-yaml', 'scikit-image', 'scikit-learn', 'scipy', 'setuptools', 'simplegeneric', 'singledispatch', 'six', 'snowballstemmer', 'sockjs-tornado', 'sortedcontainers', 'sphinx-rtd-theme', 'spyder', 'SQLAlchemy', 'statsmodels', 'stringparser', 'sympy', 'tables', 'terminado', 'toolz', 'tornado', 'traitlets', 'unicodecsv', 'vega', 'Werkzeug', 'wheel', 'xarray', 'xlrd', 'XlsxWriter', 'xlwings', 'xlwt', 'appscript', 'scikit-rf'] : pip should list Python-contrib-nbextensions as installed
-------------------- >> begin captured stdout << ---------------------
Collecting https://github.com/ipython-contrib/IPython-notebook-extensions/archive/c6d65e7826657a23c47b1fadbf8557a06e774db2.zip
  Looking up "https://github.com/ipython-contrib/IPython-notebook-extensions/archive/c6d65e7826657a23c47b1fadbf8557a06e774db2.zip" in the cache
  Returning cached "301 Moved Permanently" response (ignoring date and etag information)
  Looking up "https://github.com/ipython-contrib/jupyter_contrib_nbextensions/archive/c6d65e7826657a23c47b1fadbf8557a06e774db2.zip" in the cache
  No cache entry available
  Starting new HTTPS connection (1): github.com
  "GET /ipython-contrib/jupyter_contrib_nbextensions/archive/c6d65e7826657a23c47b1fadbf8557a06e774db2.zip HTTP/1.1" 302 None
  Looking up "https://codeload.github.com/ipython-contrib/jupyter_contrib_nbextensions/zip/c6d65e7826657a23c47b1fadbf8557a06e774db2" in the cache
  Current age based on date: 7
  Starting new HTTPS connection (1): codeload.github.com
  "GET /ipython-contrib/jupyter_contrib_nbextensions/zip/c6d65e7826657a23c47b1fadbf8557a06e774db2 HTTP/1.1" 200 12829407
  Downloading https://github.com/ipython-contrib/IPython-notebook-extensions/archive/c6d65e7826657a23c47b1fadbf8557a06e774db2.zip (12.8MB)
  Downloading from URL https://github.com/ipython-contrib/IPython-notebook-extensions/archive/c6d65e7826657a23c47b1fadbf8557a06e774db2.zip
  Updating cache with response from "https://codeload.github.com/ipython-contrib/jupyter_contrib_nbextensions/zip/c6d65e7826657a23c47b1fadbf8557a06e774db2"
  Caching due to etag
  Running setup.py (path:/var/folders/ch/yvjnrr5j62b6b5lsvgctsrk40000gn/T/pip-q2zm_7j0-build/setup.py) egg_info for package from https://github.com/ipython-contrib/IPython-notebook-extensions/archive/c6d65e7826657a23c47b1fadbf8557a06e774db2.zip
    Running command python setup.py egg_info

    *********************************************************************************************************
    IPython-contrib-nbextensions - (C) 2013-2016, IPython-contrib Developers - All rights reserved.

    contains a collection of extensions that add functionality to the Jupyter notebook. These extensions are
    mostly written in Javascript and will be loaded locally in your Browser.

    The IPython-contrib repository https://github.com/ipython-contrib/IPython-notebook-extensions
    is maintained independently by a group of users and developers and not officially related to the
    IPython development team.

    The maturity of the provided extensions may vary, please create an issue if you encounter any problems.

    Released under Modified BSD License, read COPYING file for more details.
    *********************************************************************************************************

    running egg_info
    creating pip-egg-info/Python_contrib_nbextensions.egg-info
    writing dependency_links to pip-egg-info/Python_contrib_nbextensions.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/Python_contrib_nbextensions.egg-info/top_level.txt
    writing requirements to pip-egg-info/Python_contrib_nbextensions.egg-info/requires.txt
    writing pip-egg-info/Python_contrib_nbextensions.egg-info/PKG-INFO
    writing manifest file 'pip-egg-info/Python_contrib_nbextensions.egg-info/SOURCES.txt'
    /Users/juhasch/anaconda3/lib/python3.5/site-packages/setuptools/dist.py:373: UserWarning: The version specified ('alpha') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
      "details." % self.metadata.version
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'pip-egg-info/Python_contrib_nbextensions.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/Python_contrib_nbextensions.egg-info/SOURCES.txt'
  Source in /var/folders/ch/yvjnrr5j62b6b5lsvgctsrk40000gn/T/pip-q2zm_7j0-build has version alpha, which satisfies requirement Python-contrib-nbextensions===alpha from https://github.com/ipython-contrib/IPython-notebook-extensions/archive/c6d65e7826657a23c47b1fadbf8557a06e774db2.zip
Requirement already satisfied (use --upgrade to upgrade): jupyter_core in /Users/juhasch/anaconda3/lib/python3.5/site-packages (from Python-contrib-nbextensions===alpha)
Requirement already satisfied (use --upgrade to upgrade): jupyter_nbextensions_configurator in /Users/juhasch/anaconda3/lib/python3.5/site-packages (from Python-contrib-nbextensions===alpha)
Requirement already satisfied (use --upgrade to upgrade): nbconvert in /Users/juhasch/anaconda3/lib/python3.5/site-packages (from Python-contrib-nbextensions===alpha)
Requirement already satisfied (use --upgrade to upgrade): notebook in /Users/juhasch/anaconda3/lib/python3.5/site-packages (from Python-contrib-nbextensions===alpha)
Requirement already satisfied (use --upgrade to upgrade): psutil>=2.2.1 in /Users/juhasch/anaconda3/lib/python3.5/site-packages (from Python-contrib-nbextensions===alpha)
Requirement already satisfied (use --upgrade to upgrade): pyyaml in /Users/juhasch/anaconda3/lib/python3.5/site-packages (from Python-contrib-nbextensions===alpha)
Requirement already satisfied (use --upgrade to upgrade): tornado in /Users/juhasch/anaconda3/lib/python3.5/site-packages (from Python-contrib-nbextensions===alpha)
Requirement already satisfied (use --upgrade to upgrade): traitlets in /Users/juhasch/anaconda3/lib/python3.5/site-packages (from Python-contrib-nbextensions===alpha)
Could not parse version from link: https://github.com/ipython-contrib/IPython-notebook-extensions/archive/c6d65e7826657a23c47b1fadbf8557a06e774db2.zip
Installing collected packages: Python-contrib-nbextensions
  Running setup.py install for Python-contrib-nbextensions: started
    Running command /Users/juhasch/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/var/folders/ch/yvjnrr5j62b6b5lsvgctsrk40000gn/T/pip-q2zm_7j0-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/ch/yvjnrr5j62b6b5lsvgctsrk40000gn/T/pip-bz8g5gvk-record/install-record.txt --single-version-externally-managed --compile
    Running source install...
    Extensions and templates path: /var/folders/ch/yvjnrr5j62b6b5lsvgctsrk40000gn/T/jupyter_2rq7dkiy/env_vars/data
    Installing Jupyter notebook extensions.
    Done!
    Configuring extensions...
    Cannot configure while the Jupyter notebook server is running
    Running setup.py install for Python-contrib-nbextensions: finished with status 'error'
Cleaning up...
  Removing source in /var/folders/ch/yvjnrr5j62b6b5lsvgctsrk40000gn/T/pip-q2zm_7j0-build
Exception information:
Traceback (most recent call last):
  File "/Users/juhasch/anaconda3/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Users/juhasch/anaconda3/lib/python3.5/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Users/juhasch/anaconda3/lib/python3.5/site-packages/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/Users/juhasch/anaconda3/lib/python3.5/site-packages/pip/req/req_install.py", line 880, in install
    spinner=spinner,
  File "/Users/juhasch/anaconda3/lib/python3.5/site-packages/pip/utils/__init__.py", line 718, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "/Users/juhasch/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/var/folders/ch/yvjnrr5j62b6b5lsvgctsrk40000gn/T/pip-q2zm_7j0-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/ch/yvjnrr5j62b6b5lsvgctsrk40000gn/T/pip-bz8g5gvk-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /var/folders/ch/yvjnrr5j62b6b5lsvgctsrk40000gn/T/pip-q2zm_7j0-build/

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 23 tests in 27.236s

FAILED (failures=2)
```

**Comment by jcb91** [comment]
it looks to me as though the install of the old repo is failing because it thinks a notebook server is running (see the line `Cannot configure while the Jupyter notebook server is running`). Since the old package version fails to pip install, it isn't found in the list of installed packages. Quite why there is (or appears to be) a notebook server running, I don't know...

**Comment by jcb91** [comment]
incidentally, I'm not really convinced that editing config while a server is running is actually a problem, and suspect that we might be better off removing the psutil check

**Comment by jcb91** [comment]
@juhasch did you get any more info on this?

**Comment by juhasch** [comment]
It runs OK now.
