### ISSUE TITLE
Printview 404

### ISSUE THREAD

**Issue by r3sist** [ipython-contrib/jupyter_contrib_nbextensions#983]
Hi!

Using Python 2 kernel, installed Printview nbextension can't generate output (eg .html), only opens a 404 page.

With Python 3 kernel it seems to be working. Also in terminal `jupyter nbconvert "x.ipynb" --template nbextensions` works. I have set *nbconvert options* to `--template nbextensions` via *nbextension config*. My environment is a *[scipy-notebook docker container](https://github.com/jupyter/docker-stacks/tree/master/scipy-notebook)*.

Do you have any suggestion what am I doing wrong?
Thank you!

**Comment by jcb91** [comment]
I guess perhaps we should use `subprocess` rather than `os.system` these days...

**Comment by r3sist** [comment]
` import os; os.system('jupyter nbconvert "x.ipynb" --template nbextensions')` only generates `[Out1] 256`. What should I get?

**Comment by jcb91** [comment]
well, presumably that means that the call ran ok - do you see the created html file in the notebook directory?

**Comment by r3sist** [comment]
No, there is no created .html in the directory. This `256` output is generated in every (empty or not) notebook.

**Comment by juhasch** [comment]
Can you try 
```
!jupyter nbconvert "x.ipynb" --template nbextensions
```
in a notebook codecell. There you should be able to see the output from nbconvert.

**Comment by r3sist** [comment]
`Traceback (most recent call last):
  File "/opt/conda/envs/python2/bin/jupyter-nbconvert", line 6, in <module>
    sys.exit(nbconvert.nbconvertapp.main())
  File "/opt/conda/envs/python2/lib/python2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/envs/python2/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/opt/conda/envs/python2/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 305, in start
    self.convert_notebooks()
  File "/opt/conda/envs/python2/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 463, in convert_notebooks
    self.exporter = cls(config=self.config)
  File "/opt/conda/envs/python2/lib/python2.7/site-packages/nbconvert/exporters/templateexporter.py", line 199, in __init__
    super(TemplateExporter, self).__init__(config=config, **kw)
  File "/opt/conda/envs/python2/lib/python2.7/site-packages/nbconvert/exporters/exporter.py", line 102, in __init__
    self._init_preprocessors()
  File "/opt/conda/envs/python2/lib/python2.7/site-packages/nbconvert/exporters/exporter.py", line 256, in _init_preprocessors
    self.register_preprocessor(preprocessor, enabled=True)
  File "/opt/conda/envs/python2/lib/python2.7/site-packages/nbconvert/exporters/exporter.py", line 217, in register_preprocessor
    preprocessor_cls = import_item(preprocessor)
  File "/opt/conda/envs/python2/lib/python2.7/site-packages/traitlets/utils/importstring.py", line 34, in import_item
    module = __import__(package, fromlist=[obj])
ImportError: No module named jupyter_contrib_nbextensions.nbconvert_support`

**Comment by jcb91** [comment]
So it seems like, because the `jupyter_contrib_nbextensions` package isn't installed in your python2 environment, nbconvert can't find the preprocessor to import.

To install into the correct environment, you can use

    conda install -n python2 jupyter_contrib_nbextensions

If you haven't added the conda-forge channel to your config, you'll need to add `-c conda-forge` before the package name too.

**Comment by r3sist** [comment]
@jcb91 @juhasch Thank you very much, that was it. 
Maybe this line would be useful in README.md :)
